export default [
    { es: "qué te gustaría beber", file: "que-te-gustaria-beber.mp3", en: "What would you like to drink?" },
    { es: "cómo estás hoy", file: "como-estas-hoy.mp3", en: "How are you today?" },
    { es: "dónde vives", file: "donde-vives.mp3", en: "Where do you live?" },
    { es: "qué quieres comer", file: "que-quieres-comer.mp3", en: "What do you want to eat?" },
    { es: "tienes hambre", file: "tienes-hambre.mp3", en: "Are you hungry?" },
    { es: "qué te gusta hacer", file: "que-te-gusta-hacer.mp3", en: "What do you like to do?" },
    { es: "a qué hora te levantas", file: "a-que-hora-te-levantas.mp3", en: "What time do you get up?" },
    { es: "quieres salir hoy", file: "quieres-salir-hoy.mp3", en: "Do you want to go out today?" },
    { es: "qué estás haciendo", file: "que-estas-haciendo.mp3", en: "What are you doing?" },
    { es: "quieres ver una película", file: "quieres-ver-una-pelicula.mp3", en: "Do you want to watch a movie?" },
    { es: "dónde está el baño", file: "donde-esta-el-bano.mp3", en: "Where is the bathroom?" },
    { es: "qué música te gusta", file: "que-musica-te-gusta.mp3", en: "What music do you like?" },
    { es: "quieres descansar", file: "quieres-descansar.mp3", en: "Do you want to rest?" },
    { es: "qué hay en la cocina", file: "que-hay-en-la-cocina.mp3", en: "What is in the kitchen?" },
    { es: "quieres ir al hotel", file: "quieres-ir-al-hotel.mp3", en: "Do you want to go to the hotel?" },
    { es: "qué fruta te gusta", file: "que-fruta-te-gusta.mp3", en: "What fruit do you like?" },
    { es: "quieres aprender más español", file: "quieres-aprender-mas-espanol.mp3", en: "Do you want to learn more Spanish?" },
    { es: "qué ves en la televisión", file: "que-ves-en-la-television.mp3", en: "What do you watch on TV?" },
    { es: "quieres pan con queso", file: "quieres-pan-con-queso.mp3", en: "Do you want bread with cheese?" },
    { es: "dónde está tu familia", file: "donde-esta-tu-familia.mp3", en: "Where is your family?" },
    { es: "quieres ir en autobús", file: "quieres-ir-en-autobus.mp3", en: "Do you want to go by bus?" },
    { es: "qué haces en casa", file: "que-haces-en-casa.mp3", en: "What do you do at home?" }
];

const CEFR_CONVERSATION_AUDIO_A2 = [
    { es: "qué haces normalmente por la mañana", file: "que-haces-normalmente-por-la-manana.mp3", en: "What do you normally do in the morning?" },
    { es: "qué te gustaría probar hoy", file: "que-te-gustaria-probar-hoy.mp3", en: "What would you like to try today?" },
    { es: "a qué hora llegaste anoche", file: "a-que-hora-llegaste-anoche.mp3", en: "What time did you arrive last night?" },
    { es: "qué almuerzas normalmente", file: "que-almuerzas-normalmente.mp3", en: "What do you normally have for lunch?" },
    { es: "qué película quieres ver", file: "que-pelicula-quieres-ver.mp3", en: "What movie do you want to watch?" },
    { es: "qué mensaje recibiste", file: "que-mensaje-recibiste.mp3", en: "What message did you receive?" },
    { es: "qué vas a cocinar esta noche", file: "que-vas-a-cocinar-esta-noche.mp3", en: "What are you going to cook tonight?" },
    { es: "qué tarea tienes hoy", file: "que-tarea-tienes-hoy.mp3", en: "What homework do you have today?" },
    { es: "qué quieres visitar en tu próximo viaje", file: "que-quieres-visitar-en-tu-proximo-viaje.mp3", en: "What do you want to visit on your next trip?" },
    { es: "conduces a menudo", file: "conduces-a-menudo.mp3", en: "Do you drive often?" },
    { es: "qué esperas hoy", file: "que-esperas-hoy.mp3", en: "What are you waiting for today?" },
    { es: "qué te gustaría olvidar", file: "que-te-gustaria-olvidar.mp3", en: "What would you like to forget?" },
    { es: "qué haces antes de dormir", file: "que-haces-antes-de-dormir.mp3", en: "What do you do before sleeping?" },
    { es: "qué haces después del almuerzo", file: "que-haces-despues-del-almuerzo.mp3", en: "What do you do after lunch?" },
    { es: "qué transporte usas normalmente", file: "que-transporte-usas-normalmente.mp3", en: "What transport do you normally use?" },
    { es: "qué cocina te gusta más", file: "que-cocina-te-gusta-mas.mp3", en: "Which kitchen do you like more?" },
    { es: "qué haces ahora", file: "que-haces-ahora.mp3", en: "What are you doing now?" },
    { es: "qué zapatos usas hoy", file: "que-zapatos-usas-hoy.mp3", en: "What shoes are you wearing today?" },
    { es: "qué te gustaría cocinar mañana", file: "que-te-gustaria-cocinar-manana.mp3", en: "What would you like to cook tomorrow?" },
    { es: "qué información necesitas", file: "que-informacion-necesitas.mp3", en: "What information do you need?" },
    { es: "qué haces cuando llegas a casa", file: "que-haces-cuando-llegas-a-casa.mp3", en: "What do you do when you arrive home?" },
    { es: "qué te gustaría visitar este año", file: "que-te-gustaria-visitar-este-ano.mp3", en: "What would you like to visit this year?" }
];

const CEFR_CONVERSATION_AUDIO_B1 = [
    { es: "qué has aprendido recientemente", file: "que-has-aprendido-recientemente.mp3", en: "What have you learned recently?" },
    { es: "qué estás estudiando ahora", file: "que-estas-estudiando-ahora.mp3", en: "What are you studying now?" },
    { es: "qué experiencias pasadas recuerdas más", file: "que-experiencias-pasadas-recuerdas-mas.mp3", en: "What past experiences do you remember most?" },
    { es: "qué habilidades quieres mejorar", file: "que-habilidades-quieres-mejorar.mp3", en: "What skills do you want to improve?" },
    { es: "qué estás trabajando esta semana", file: "que-estas-trabajando-esta-semana.mp3", en: "What are you working on this week?" },
    { es: "qué conversaciones tienes a menudo", file: "que-conversaciones-tienes-a-menudo.mp3", en: "What conversations do you often have?" },
    { es: "qué has estado haciendo últimamente", file: "que-has-estado-haciendo-ultimamente.mp3", en: "What have you been doing lately?" },
    { es: "qué quieres conseguir este mes", file: "que-quieres-conseguir-este-mes.mp3", en: "What do you want to achieve this month?" },
    { es: "qué te gustaría continuar aprendiendo", file: "que-te-gustaria-continuar-aprendiendo.mp3", en: "What would you like to continue learning?" },
    { es: "qué tipo de comunicación es importante para ti", file: "que-tipo-de-comunicacion-es-importante-para-ti.mp3", en: "What type of communication is important to you?" },
    { es: "qué has estado leyendo últimamente", file: "que-has-estado-leyendo-ultimamente.mp3", en: "What have you been reading lately?" },
    { es: "qué te gustaría preparar mañana", file: "que-te-gustaria-preparar-manana.mp3", en: "What would you like to prepare tomorrow?" },
    { es: "qué te gustaría cambiar este año", file: "que-te-gustaria-cambiar-este-ano.mp3", en: "What would you like to change this year?" },
    { es: "qué te gustaría seguir haciendo", file: "que-te-gustaria-seguir-haciendo.mp3", en: "What would you like to keep doing?" },
    { es: "qué tipo de tareas tienes esta semana", file: "que-tipo-de-tareas-tienes-esta-semana.mp3", en: "What tasks do you have this week?" },
    { es: "qué te gustaría encontrar hoy", file: "que-te-gustaria-encontrar-hoy.mp3", en: "What would you like to find today?" },
    { es: "qué te gustaría cancelar este mes", file: "que-te-gustaria-cancelar-este-mes.mp3", en: "What would you like to cancel this month?" },
    { es: "qué te gustaría traer a la reunión", file: "que-te-gustaria-traer-a-la-reunion.mp3", en: "What would you like to bring to the meeting?" },
    { es: "qué planeas hacer mañana", file: "que-planeas-hacer-manana.mp3", en: "What do you plan to do tomorrow?" },
    { es: "qué te gustaría entender mejor", file: "que-te-gustaria-entender-mejor.mp3", en: "What would you like to understand better?" },
    { es: "qué te gustaría seguir revisando", file: "que-te-gustaria-seguir-revisando.mp3", en: "What would you like to keep reviewing?" }
];

const CEFR_CONVERSATION_AUDIO_B2 = [
    { es: "qué estrategia usas para aprender mejor", file: "que-estrategia-usas-para-aprender-mejor.mp3", en: "What strategy do you use to learn better?" },
    { es: "cómo evalúas tu rendimiento en el trabajo", file: "como-evaluas-tu-rendimiento-en-el-trabajo.mp3", en: "How do you evaluate your performance at work?" },
    { es: "qué concepto te parece complicado últimamente", file: "que-concepto-te-parece-complicado-ultimamente.mp3", en: "What concept seems complicated to you lately?" },
    { es: "qué riesgo consideras importante en tu trabajo", file: "que-riesgo-consideras-importante-en-tu-trabajo.mp3", en: "What risk do you consider important in your work?" },
    { es: "qué posibilidad te gustaría explorar", file: "que-posibilidad-te-gustaria-explorar.mp3", en: "What possibility would you like to explore?" },
    { es: "qué situación te ha afectado recientemente", file: "que-situacion-te-ha-afectado-recientemente.mp3", en: "What situation has affected you recently?" },
    { es: "cómo optimizas tu tiempo cada día", file: "como-optimizas-tu-tiempo-cada-dia.mp3", en: "How do you optimize your time each day?" },
    { es: "qué enfoque profesional te funciona mejor", file: "que-enfoque-profesional-te-funciona-mejor.mp3", en: "What professional approach works best for you?" },
    { es: "qué tarea te gustaría actualizar", file: "que-tarea-te-gustaria-actualizar.mp3", en: "What task would you like to update?" },
    { es: "qué has analizado esta semana", file: "que-has-analizado-esta-semana.mp3", en: "What have you analyzed this week?" },
    { es: "qué te gustaría discutir con tu equipo", file: "que-te-gustaria-discutir-con-tu-equipo.mp3", en: "What would you like to discuss with your team?" },
    { es: "qué has logrado este mes", file: "que-has-logrado-este-mes.mp3", en: "What have you achieved this month?" },
    { es: "qué cultura te interesa explorar", file: "que-cultura-te-interesa-explorar.mp3", en: "What culture are you interested in exploring?" },
    { es: "qué desafíos has enfrentado recientemente", file: "que-desafios-has-enfrentado-recientemente.mp3", en: "What challenges have you faced recently?" },
    { es: "qué expectativas tienes para este año", file: "que-expectativas-tienes-para-este-ano.mp3", en: "What expectations do you have for this year?" },
    { es: "qué situación te gustaría aclarar", file: "que-situacion-te-gustaria-aclarar.mp3", en: "What situation would you like to clarify?" },
    { es: "qué proceso te gustaría optimizar", file: "que-proceso-te-gustaria-optimizar.mp3", en: "What process would you like to optimize?" },
    { es: "qué información has evaluado recientemente", file: "que-informacion-has-evaluado-recientemente.mp3", en: "What information have you evaluated recently?" },
    { es: "qué idea te gustaría fortalecer", file: "que-idea-te-gustaria-fortalecer.mp3", en: "What idea would you like to strengthen?" },
    { es: "qué tema te gustaría discutir más profundamente", file: "que-tema-te-gustaria-discutir-mas-profundamente.mp3", en: "What topic would you like to discuss more deeply?" },
    { es: "qué enfoque te gustaría adaptar este año", file: "que-enfoque-te-gustaria-adaptar-este-ano.mp3", en: "What approach would you like to adapt this year?" }
];
