
export default {
        A1: [
        { spanish: "vivir", english: "to live", category: "Daily Life" },
        { spanish: "trabajar", english: "to work", category: "Daily Life" },
        { spanish: "estudiar", english: "to study", category: "Daily Life" },
        { spanish: "leer", english: "to read", category: "Daily Life" },
        { spanish: "libros", english: "books", category: "Daily Life" },
        { spanish: "hora", english: "hour", category: "Daily Life" },
        { spanish: "levantarse", english: "to get up", category: "Daily Life" },
        { spanish: "música", english: "music", category: "Daily Life" },
        { spanish: "televisión", english: "television", category: "Daily Life" },
        { spanish: "limpiar", english: "to clean", category: "Daily Life" },
        { spanish: "cocinar", english: "to cook", category: "Daily Life" },
        { spanish: "abrir", english: "to open", category: "Daily Life" },
        { spanish: "terminar", english: "to finish", category: "Daily Life" },
        { spanish: "escribir", english: "to write", category: "Daily Life" },
        { spanish: "aprender", english: "to learn", category: "Daily Life" },
        { spanish: "ir", english: "to go", category: "Daily Life" },
        { spanish: "hacer", english: "to do", category: "Daily Life" },
        { spanish: "ver", english: "to see", category: "Daily Life" },
        { spanish: "escuchar", english: "to listen", category: "Daily Life" },
        { spanish: "salir", english: "to go out", category: "Daily Life" },
        { spanish: "descansar", english: "to rest", category: "Daily Life" },
        { spanish: "caliente", english: "hot", category: "Daily Life" },
        { spanish: "frío", english: "cold", category: "Daily Life" },
        { spanish: "feliz", english: "happy", category: "Daily Life" },
        { spanish: "nuevo", english: "new", category: "Daily Life" },
        { spanish: "hola", english: "hello", category: "Daily Life" },
        { spanish: "adiós", english: "goodbye", category: "Daily Life" },
        { spanish: "gracias", english: "thank you", category: "Daily Life" },
        { spanish: "siento", english: "sorry / I feel", category: "Daily Life" },
        { spanish: "estás", english: "you are", category: "Daily Life" },
        { spanish: "listos", english: "ready", category: "Daily Life" },
        { spanish: "despierto", english: "awake", category: "Daily Life" },
        { spanish: "tiempo", english: "time", category: "Daily Life" },
        { spanish: "problemas", english: "problems", category: "Daily Life" },
        { spanish: "cambio", english: "change", category: "Daily Life" },
        { spanish: "buenos días", english: "good morning", category: "Daily Life" },
        { spanish: "buenas tardes", english: "good afternoon", category: "Daily Life" },
        { spanish: "buenas noches", english: "good night", category: "Daily Life" },
        { spanish: "bien", english: "well / good", category: "Daily Life" },
        { spanish: "señor", english: "sir", category: "Daily Life" },
        { spanish: "señora", english: "ma'am", category: "Daily Life" },

        { spanish: "familia", english: "family", category: "Family" },
        { spanish: "madre", english: "mother", category: "Family" },
        { spanish: "padre", english: "father", category: "Family" },
        { spanish: "hijo", english: "son", category: "Family" },
        { spanish: "hija", english: "daughter", category: "Family" },
        { spanish: "amigo", english: "friend", category: "Family" },
        { spanish: "amiga", english: "friend (female)", category: "Family" },
        { spanish: "hermana", english: "sister", category: "Family" },
        { spanish: "hermanos", english: "brothers", category: "Family" },
        { spanish: "hermanas", english: "sisters", category: "Family" },
        { spanish: "abuela", english: "grandmother", category: "Family" },
        { spanish: "hambre", english: "hunger", category: "Family" },
        { spanish: "tenemos", english: "we have", category: "Family" },
        { spanish: "tienen", english: "they have", category: "Family" },

        { spanish: "agua", english: "water", category: "Food & Drink" },
        { spanish: "comida", english: "food", category: "Food & Drink" },
        { spanish: "café", english: "coffee", category: "Food & Drink" },
        { spanish: "té", english: "tea", category: "Food & Drink" },
        { spanish: "leche", english: "milk", category: "Food & Drink" },
        { spanish: "filete", english: "steak", category: "Food & Drink" },
        { spanish: "papas fritas", english: "french fries", category: "Food & Drink" },
        { spanish: "pan", english: "bread", category: "Food & Drink" },
        { spanish: "cerveza", english: "beer", category: "Food & Drink" },
        { spanish: "huevo", english: "egg", category: "Food & Drink" },
        { spanish: "fruta", english: "fruit", category: "Food & Drink" },
        { spanish: "manzana", english: "apple", category: "Food & Drink" },
        { spanish: "naranja", english: "orange", category: "Food & Drink" },
        { spanish: "plátano", english: "banana", category: "Food & Drink" },
        { spanish: "pollo", english: "chicken", category: "Food & Drink" },
        { spanish: "pescado", english: "fish", category: "Food & Drink" },
        { spanish: "sopa", english: "soup", category: "Food & Drink" },
        { spanish: "ensalada", english: "salad", category: "Food & Drink" },
        { spanish: "arroz", english: "rice", category: "Food & Drink" },
        { spanish: "frijoles", english: "beans", category: "Food & Drink" },
        { spanish: "queso", english: "cheese", category: "Food & Drink" },
        { spanish: "sal", english: "salt", category: "Food & Drink" },

        { spanish: "autobús", english: "bus", category: "Travel" },
        { spanish: "tren", english: "train", category: "Travel" },
        { spanish: "boleto", english: "ticket", category: "Travel" },
        { spanish: "estación", english: "station", category: "Travel" },
        { spanish: "aeropuerto", english: "airport", category: "Travel" },
        { spanish: "casa", english: "house", category: "Travel" },
        { spanish: "escuela", english: "school", category: "Travel" },
        { spanish: "hotel", english: "hotel", category: "Travel" },
        { spanish: "baño", english: "bathroom", category: "Travel" },
        { spanish: "lugar", english: "place", category: "Travel" },

        { spanish: "y", english: "and", category: "Connectors" },
        { spanish: "o", english: "or", category: "Connectors" },
        { spanish: "con", english: "with", category: "Connectors" },
        { spanish: "sin", english: "without", category: "Connectors" },
        { spanish: "más", english: "more", category: "Connectors" },
        { spanish: "poco", english: "little", category: "Connectors" },
        { spanish: "solo", english: "only", category: "Connectors" },
        { spanish: "muy", english: "very", category: "Connectors" },
        { spanish: "cerca", english: "near", category: "Connectors" },
        { spanish: "para", english: "for", category: "Connectors" },
        { spanish: "a", english: "to", category: "Connectors" },
        { spanish: "en", english: "in", category: "Connectors" },
        { spanish: "ella", english: "she", category: "Connectors" },
        { spanish: "el", english: "he", category: "Connectors" },
        { spanish: "ellos", english: "they", category: "Connectors" },
        { spanish: "su", english: "his / her / their", category: "Connectors" },
        { spanish: "qué", english: "what", category: "Connectors" },
        { spanish: "quién", english: "who", category: "Connectors" },
        { spanish: "cuándo", english: "when", category: "Connectors" },
        { spanish: "cómo", english: "how", category: "Connectors" },
        { spanish: "cuál", english: "which", category: "Connectors" },
        { spanish: "dónde", english: "where", category: "Connectors" },
        { spanish: "no", english: "no / not", category: "Connectors" },
        { spanish: "si", english: "yes", category: "Connectors" },
        { spanish: "hay", english: "there is / there are", category: "Connectors" },
        { spanish: "otra", english: "other / another", category: "Connectors" },
        { spanish: "pesar", english: "despite", category: "Connectors" },
        { spanish: "por favor", english: "please", category: "Connectors" },
        { spanish: "me", english: "myself / to me", category: "Connectors" },
        { spanish: "mi", english: "my", category: "Connectors" },
        { spanish: "un", english: "a / an (masculine)", category: "Connectors" },
        { spanish: "una", english: "a / an (feminine)", category: "Connectors" },
        { spanish: "el", english: "the (masculine)", category: "Connectors" },
        { spanish: "la", english: "the (feminine)", category: "Connectors" },

        { spanish: "es", english: "is", category: "Verbs" },
        { spanish: "gusta", english: "likes", category: "Verbs" },
        { spanish: "gustan", english: "they like", category: "Verbs" },
        { spanish: "gustaría", english: "would like", category: "Verbs" },
        { spanish: "aprendiendo", english: "learning", category: "Verbs" },
        { spanish: "arreglando", english: "fixing", category: "Verbs" },
        { spanish: "está", english: "is / you are (formal)", category: "Verbs" },
        { spanish: "quiero", english: "I want", category: "Verbs" },
        { spanish: "tengo", english: "I have", category: "Verbs" },
        { spanish: "necesito", english: "I need", category: "Verbs" },

        { spanish: "bueno", english: "good", category: "Adjectives" },
        { spanish: "difícil", english: "difficult", category: "Adjectives" },
        { spanish: "clara", english: "clear", category: "Adjectives" },
        { spanish: "fácil", english: "easy", category: "Adjectives" },
        { spanish: "malo", english: "bad", category: "Adjectives" },
        { spanish: "pequeño", english: "small", category: "Adjectives" },

        { spanish: "uno", english: "one", category: "Numbers" },
        { spanish: "dos", english: "two", category: "Numbers" },
        { spanish: "tres", english: "three", category: "Numbers" },
        { spanish: "cuatro", english: "four", category: "Numbers" },
        { spanish: "cinco", english: "five", category: "Numbers" },
        { spanish: "seis", english: "six", category: "Numbers" },
        { spanish: "siete", english: "seven", category: "Numbers" },
        { spanish: "ocho", english: "eight", category: "Numbers" },
        { spanish: "nueve", english: "nine", category: "Numbers" },
        { spanish: "diez", english: "ten", category: "Numbers" }
    ],

    A2: [
        { spanish: "desayuno", english: "breakfast", category: "Daily Life" },
        { spanish: "almuerzo", english: "lunch", category: "Daily Life" },
        { spanish: "cena", english: "dinner", category: "Daily Life" },
        { spanish: "temprano", english: "early", category: "Daily Life" },
        { spanish: "tarde", english: "late", category: "Daily Life" },
        { spanish: "anoche", english: "last night", category: "Daily Life" },
        { spanish: "ahora", english: "now", category: "Daily Life" },
        { spanish: "minutos", english: "minutes", category: "Daily Life" },
        { spanish: "tarea", english: "homework", category: "Daily Life" },
        { spanish: "mensaje", english: "message", category: "Daily Life" },
        { spanish: "información", english: "information", category: "Daily Life" },
        { spanish: "película", english: "movie", category: "Daily Life" },
        { spanish: "ventana", english: "window", category: "Daily Life" },
        { spanish: "cocina", english: "kitchen", category: "Daily Life" },
        { spanish: "zapatos", english: "shoes", category: "Daily Life" },
        { spanish: "viaje", english: "trip", category: "Daily Life" },
        { spanish: "probar", english: "to try", category: "Daily Life" },
        { spanish: "olvidar", english: "to forget", category: "Daily Life" },
        { spanish: "esperar", english: "to wait", category: "Daily Life" },
        { spanish: "conducir", english: "to drive", category: "Daily Life" },
        { spanish: "arreglar", english: "to fix", category: "Daily Life" },
        { spanish: "irse", english: "to leave", category: "Daily Life" },
        { spanish: "llegar", english: "to arrive", category: "Daily Life" },

        { spanish: "padres", english: "parents", category: "Family" },

        { spanish: "avión", english: "plane", category: "Travel" },
        { spanish: "visitar", english: "to visit", category: "Travel" },
        { spanish: "transporte", english: "transport", category: "Travel" },

        { spanish: "a menudo", english: "often", category: "Connectors" },
        { spanish: "antes", english: "before", category: "Connectors" },
        { spanish: "ya", english: "already", category: "Connectors" },
        { spanish: "todavía", english: "still", category: "Connectors" },
        { spanish: "normalmente", english: "normally", category: "Connectors" },
        { spanish: "porque", english: "because", category: "Connectors" },

        { spanish: "once", english: "eleven", category: "Numbers" },
        { spanish: "doce", english: "twelve", category: "Numbers" },
        { spanish: "trece", english: "thirteen", category: "Numbers" },
        { spanish: "catorce", english: "fourteen", category: "Numbers" },
        { spanish: "quince", english: "fifteen", category: "Numbers" },
        { spanish: "dieisiete", english: "sixteen", category: "Numbers" },
        { spanish: "diecisiete", english: "seventeen", category: "Numbers" },
        { spanish: "dieciocho", english: "eighteen", category: "Numbers" },
        { spanish: "diecinueve", english: "nineteen", category: "Numbers" },
        { spanish: "veinte", english: "twenty", category: "Numbers" }
    ],

    B1: [
        { spanish: "he", english: "I have (auxiliary)", category: "Daily Life" },
        { spanish: "has", english: "you have (auxiliary)", category: "Daily Life" },
        { spanish: "ha", english: "he/she has (auxiliary)", category: "Daily Life" },
        { spanish: "hemos", english: "we have (auxiliary)", category: "Daily Life" },
        { spanish: "habéis", english: "you (plural) have (auxiliary)", category: "Daily Life" },
        { spanish: "han", english: "they have (auxiliary)", category: "Daily Life" },

        { spanish: "estado", english: "been", category: "Daily Life" },
        { spanish: "aprendido", english: "learned", category: "Daily Life" },
        { spanish: "trabajando", english: "working", category: "Daily Life" },
        { spanish: "estudiando", english: "studying", category: "Daily Life" },
        { spanish: "leyendo", english: "reading", category: "Daily Life" },
        { spanish: "viviendo", english: "living", category: "Daily Life" },
        { spanish: "diarias", english: "daily", category: "Daily Life" },

        { spanish: "comunicación", english: "communication", category: "Daily Life" },
        { spanish: "conversaciones", english: "conversations", category: "Daily Life" },
        { spanish: "mejorar", english: "to improve", category: "Daily Life" },
        { spanish: "habilidades", english: "skills", category: "Daily Life" },
        { spanish: "revisar", english: "to review", category: "Daily Life" },
        { spanish: "continuar", english: "to continue", category: "Daily Life" },
        { spanish: "seguir", english: "to follow", category: "Daily Life" },
        { spanish: "preparar", english: "to prepare", category: "Daily Life" },
        { spanish: "conseguir", english: "to get", category: "Daily Life" },
        { spanish: "entender", english: "to understand", category: "Daily Life" },

        { spanish: "experiencias", english: "experiences", category: "Family" },
        { spanish: "pasadas", english: "past", category: "Family" },

        { spanish: "restaurante", english: "restaurant", category: "Food & Drink" },
        { spanish: "menú", english: "menu", category: "Food & Drink" },
        { spanish: "cuenta", english: "bill", category: "Food & Drink" },

        { spanish: "encontrar", english: "to find", category: "Travel" },
        { spanish: "cancelar", english: "to cancel", category: "Travel" },
        { spanish: "traer", english: "to bring", category: "Travel" },
        { spanish: "planear", english: "to plan", category: "Travel" },
        { spanish: "mudarse", english: "to move (house)", category: "Travel" },
        { spanish: "unirse", english: "to join", category: "Travel" },

        { spanish: "mientras", english: "while", category: "Connectors" },
        { spanish: "sin embargo", english: "however", category: "Connectors" },
        { spanish: "sobre", english: "about", category: "Connectors" },
        { spanish: "después", english: "after", category: "Connectors" },
        { spanish: "durante", english: "during", category: "Connectors" },

        { spanish: "mes", english: "month", category: "Numbers" },
        { spanish: "años", english: "years", category: "Numbers" }
    ],
    B2: [
        { spanish: "proceso", english: "process", category: "Daily Life" },
        { spanish: "resultados", english: "results", category: "Daily Life" },
        { spanish: "rendimiento", english: "performance", category: "Daily Life" },
        { spanish: "estrategia", english: "strategy", category: "Daily Life" },
        { spanish: "sistema", english: "system", category: "Daily Life" },
        { spanish: "enfoque", english: "approach", category: "Daily Life" },
        { spanish: "concepto", english: "concept", category: "Daily Life" },
        { spanish: "riesgo", english: "risk", category: "Daily Life" },
        { spanish: "posibilidad", english: "possibility", category: "Daily Life" },
        { spanish: "situación", english: "situation", category: "Daily Life" },

        { spanish: "optimizar", english: "to optimize", category: "Daily Life" },
        { spanish: "coordinar", english: "to coordinate", category: "Daily Life" },
        { spanish: "aumentar", english: "to increase", category: "Daily Life" },
        { spanish: "actualizar", english: "to update", category: "Daily Life" },
        { spanish: "analizar", english: "to analyze", category: "Daily Life" },
        { spanish: "evaluar", english: "to evaluate", category: "Daily Life" },
        { spanish: "discutir", english: "to discuss", category: "Daily Life" },
        { spanish: "aclarar", english: "to clarify", category: "Daily Life" },
        { spanish: "fortalecer", english: "to strengthen", category: "Daily Life" },
        { spanish: "adaptarse", english: "to adapt", category: "Daily Life" },
        { spanish: "lograr", english: "to achieve", category: "Daily Life" },

        { spanish: "complicado", english: "complicated", category: "Daily Life" },
        { spanish: "necesario", english: "necessary", category: "Daily Life" },
        { spanish: "posible", english: "possible", category: "Daily Life" },
        { spanish: "efectivo", english: "effective", category: "Daily Life" },
        { spanish: "realista", english: "realistic", category: "Daily Life" },
        { spanish: "innovadora", english: "innovative", category: "Daily Life" },
        { spanish: "profesional", english: "professional", category: "Daily Life" },
        { spanish: "positivo", english: "positive", category: "Daily Life" },

        { spanish: "analizado", english: "analyzed", category: "Daily Life" },
        { spanish: "evaluado", english: "evaluated", category: "Daily Life" },
        { spanish: "argumentado", english: "argued", category: "Daily Life" },
        { spanish: "ampliado", english: "expanded", category: "Daily Life" },
        { spanish: "adaptado", english: "adapted", category: "Daily Life" },
        { spanish: "reducido", english: "reduced", category: "Daily Life" },
        { spanish: "insistido", english: "insisted", category: "Daily Life" },
        { spanish: "explorado", english: "explored", category: "Daily Life" },
        { spanish: "aclarado", english: "clarified", category: "Daily Life" },
        { spanish: "fortalecido", english: "strengthened", category: "Daily Life" },
        { spanish: "discutido", english: "discussed", category: "Daily Life" },
        { spanish: "actualizado", english: "updated", category: "Daily Life" },
        { spanish: "optimizado", english: "optimized", category: "Daily Life" },

        { spanish: "sociedad", english: "society", category: "Family" },
        { spanish: "cultura", english: "culture", category: "Family" },
        { spanish: "motivación", english: "motivation", category: "Family" },
        { spanish: "desafíos", english: "challenges", category: "Family" },
        { spanish: "expectativas", english: "expectations", category: "Family" },

        { spanish: "remoto", english: "remote", category: "Travel" },
        { spanish: "futuro", english: "future", category: "Travel" },
        { spanish: "largo plazo", english: "long term", category: "Travel" },

        { spanish: "además", english: "in addition", category: "Connectors" },
        { spanish: "por lo tanto", english: "therefore", category: "Connectors" },
        { spanish: "a pesar de", english: "despite", category: "Connectors" },
        { spanish: "aunque", english: "although", category: "Connectors" },
        { spanish: "incluso", english: "even", category: "Connectors" },
        { spanish: "otra vez", english: "again", category: "Connectors" },
        { spanish: "cuidadosamente", english: "carefully", category: "Connectors" }
    ],
};

  
