

export default {
    "Open Cut Mining": [
        { spanish: "rampa de acceso", english: "access ramp", category: "Open Cut Mining" },
        { spanish: "ángulo de reposo", english: "angle of repose", category: "Open Cut Mining" },
        { spanish: "minería con barreno", english: "auger mining", category: "Open Cut Mining" },
        { spanish: "excavadora de cuchara frontal", english: "backhoe excavator", category: "Open Cut Mining" },
        { spanish: "banco", english: "bench", category: "Open Cut Mining" },
        { spanish: "berma", english: "berm", category: "Open Cut Mining" },
        { spanish: "malla de perforación", english: "blast pattern", category: "Open Cut Mining" },
        { spanish: "corte de caja", english: "box cut", category: "Open Cut Mining" },
        { spanish: "minería masiva", english: "bulk mining", category: "Open Cut Mining" },
        { spanish: "banco de contención", english: "catch bench", category: "Open Cut Mining" },
        { spanish: "cresta", english: "crest", category: "Open Cut Mining" },
        { spanish: "tolva de bulldozer", english: "dozer trap", category: "Open Cut Mining" },
        { spanish: "dragalina", english: "dragline", category: "Open Cut Mining" },
        { spanish: "perforadora de pozos de voladura", english: "drill rig (rotary blasthole)", category: "Open Cut Mining" },
        { spanish: "botadero", english: "dump / waste dump", category: "Open Cut Mining" },
        { spanish: "pala eléctrica de cables", english: "electric rope shovel", category: "Open Cut Mining" },
        { spanish: "botadero externo", english: "ex-pit dump", category: "Open Cut Mining" },
        { spanish: "frente de explotación", english: "face", category: "Open Cut Mining" },
        { spanish: "control de leyes", english: "grade control", category: "Open Cut Mining" },
        { spanish: "camino de acarreo", english: "haul road", category: "Open Cut Mining" },
        { spanish: "talud alto", english: "highwall", category: "Open Cut Mining" },
        { spanish: "sistema de chancado y transportadores en pit", english: "in-pit crushing and conveying (IPCC)", category: "Open Cut Mining" },
        { spanish: "botadero interno", english: "in-pit dump", category: "Open Cut Mining" },
        { spanish: "altura de banco", english: "lift", category: "Open Cut Mining" },
        { spanish: "carga y acarreo", english: "load-and-haul", category: "Open Cut Mining" },
        { spanish: "talud bajo", english: "lowwall", category: "Open Cut Mining" },
        { spanish: "vida útil de la mina", english: "mine life", category: "Open Cut Mining" },
        { spanish: "plan de minado", english: "mine plan", category: "Open Cut Mining" },
        { spanish: "chancadora móvil", english: "mobile crusher", category: "Open Cut Mining" },
        { spanish: "pila de material volado", english: "muckpile", category: "Open Cut Mining" },
        { spanish: "minería a cielo abierto", english: "open-cut / open-pit", category: "Open Cut Mining" },
        { spanish: "recubrimiento", english: "overburden", category: "Open Cut Mining" },
        { spanish: "talud perimetral", english: "perimeter bund", category: "Open Cut Mining" },
        { spanish: "piso del tajo", english: "pit floor", category: "Open Cut Mining" },
        { spanish: "límite final del tajo", english: "pit limit / ultimate pit limit", category: "Open Cut Mining" },
        { spanish: "cantera", english: "quarry", category: "Open Cut Mining" },
        { spanish: "remanejo", english: "rehandle", category: "Open Cut Mining" },
        { spanish: "rehabilitación ambiental", english: "rehabilitation", category: "Open Cut Mining" },
        { spanish: "perforadora rotativa", english: "rotary blasthole drill", category: "Open Cut Mining" },
        { spanish: "cancha rom", english: "run-of-mine (rom) pad", category: "Open Cut Mining" },
        { spanish: "pretil de seguridad", english: "safety bund", category: "Open Cut Mining" },
        { spanish: "retiro de gruesos", english: "scalping", category: "Open Cut Mining" },
        { spanish: "estabilidad de taludes", english: "slope stability", category: "Open Cut Mining" },
        { spanish: "relación de stripping", english: "stripping ratio", category: "Open Cut Mining" },
        { spanish: "minador de superficie", english: "surface miner", category: "Open Cut Mining" },
        { spanish: "pata de talud", english: "toe", category: "Open Cut Mining" },
        { spanish: "retiro de capa vegetal", english: "topsoil stripping", category: "Open Cut Mining" },
        { spanish: "plan de gestión de tráfico", english: "traffic management plan", category: "Open Cut Mining" },
        { spanish: "tajo final", english: "ultimate pit", category: "Open Cut Mining" },
        { spanish: "cargador frontal de neumáticos", english: "wheel loader", category: "Open Cut Mining" }
    ],
    "Underground Mining": [
        { spanish: "socavón", english: "adit", category: "Underground Mining" },
        { spanish: "relleno", english: "backfill", category: "Underground Mining" },
        { spanish: "hundimiento por bloques", english: "block caving", category: "Underground Mining" },
        { spanish: "pilar de bloque", english: "block pillar", category: "Underground Mining" },
        { spanish: "tolva de extracción", english: "drawbell", category: "Underground Mining" },
        { spanish: "punto de extracción", english: "drawpoint", category: "Underground Mining" },
        { spanish: "hundimiento masivo", english: "caving", category: "Underground Mining" },
        { spanish: "crucero", english: "crosscut", category: "Underground Mining" },
        { spanish: "galería", english: "drift", category: "Underground Mining" },
        { spanish: "muro", english: "footwall", category: "Underground Mining" },
        { spanish: "techo", english: "hanging wall", category: "Underground Mining" },
        { spanish: "explotación por minas largas", english: "longwall mining", category: "Underground Mining" },
        { spanish: "nivel de producción", english: "production level", category: "Underground Mining" },
        { spanish: "chimenea", english: "raise", category: "Underground Mining" },
        { spanish: "pique", english: "shaft", category: "Underground Mining" },
        { spanish: "tajeo", english: "stope", category: "Underground Mining" },
        { spanish: "subsidencia", english: "subsidence", category: "Underground Mining" },
        { spanish: "socavación", english: "undercut", category: "Underground Mining" },
        { spanish: "nivel de socavación", english: "undercut level", category: "Underground Mining" },
        { spanish: "contrapique", english: "winze", category: "Underground Mining" }
    ]
};

