 

export default {
  
    "can": "puedo / puedes / puede",
    "buy": "comprar",
    "order": "pedir",
    "the": "el / la / los / las",
    "a": "un / una",
    "an": "un / una",
    "is": "es / está",
    "are": "son / están",
    "want": "quiero / quiere / queremos / quieren",
    "need": "necesito / necesita / necesitamos / necesitan",

   
    "puedo": "I can",
    "puedes": "you can (informal)",
    "puede": "he / she / you (formal) can",
    "podemos": "we can",
    "pueden": "they / you all can",
    "quieres": "you want (informal)",
    "necesitas": "you need (informal)",
    "tienes": "you have (informal)",
    "haces": "you do / you make",
    "compro": "I buy",
    "compras": "you buy",
    "pido": "I order / I request",
    "pides": "you order",

     
    "buena": "good (fem.)",
    "buenos": "good (plural)",
    "buenas": "good (fem. plural)",
    "mala": "bad (fem.)",
    "malos": "bad (plural)",
    "malas": "bad (fem. plural)",
    "nueva": "new (fem.)",
    "nuevos": "new (plural)",
    "nuevas": "new (fem. plural)",
    "pequeña": "small (fem.)",
    "pequeños": "small (plural)",
    "pequeñas": "small (fem. plural)",
    "fría": "cold (fem.)",
    "fríos": "cold (plural)",
    "frías": "cold (fem. plural)",
    "grandes": "big / large (plural)",
    "altos": "tall (plural)",
    "altas": "tall (fem. plural)",
    "limpia": "clean (fem.)",
    "limpios": "clean (plural)",

     
    "y": "and",
    "o": "or",
    "con": "with",
    "sin": "without",
    "más": "more",
    "poco": "little",
    "solo": "only / alone",
    "muy": "very",
    "cerca": "near",
    "para": "for",
    "a": "to",
    "en": "in / on",
    "por": "for / by",
    "de": "of / from",
    "al": "to the",
    "del": "of the",
    "pero": "but",
    "porque": "because",
    "también": "also",
    "entonces": "then",
    "si": "yes / if",
    "hay": "there is / there are",
    "otra": "other / another",
    "otro": "other / another (masc.)",
    "otras": "other / another (plural)",
    "otros": "other / another (masc. plural)",
    "pesar": "despite",
    "a pesar de": "despite",
    "favor": "favor",
    "por favor": "please",
    "mientras": "while",
    "sin embargo": "however",
    "sobre": "about / on top of",
    "después": "after",
    "durante": "during",
    "además": "in addition / furthermore",
    "por lo tanto": "therefore",
    "aunque": "although",
    "incluso": "even",
    "otra vez": "again",

    
    "qué": "what",
    "quién": "who",
    "cuándo": "when",
    "cómo": "how",
    "cuál": "which",
    "dónde": "where",
    "por qué": "why",

    
    "el": "the",
    "la": "the",
    "los": "the (plural)",
    "las": "the (fem. plural)",
    "un": "a / an",
    "una": "a / an (fem.)",
    "unos": "some",
    "unas": "some (fem.)",
    
    "me": "me / myself",
    "te": "you / yourself",
    "le": "to him / to her",
    "nos": "us / ourselves",
    "les": "to them",
    "lo": "it / him",
    "la_pronoun": "it / her",
    "los_pronoun": "them (masc.)",
    "las_pronoun": "them (fem.)",
    "que": "that / which",
    "él": "he",
    "ella": "she",
    "yo": "I",
    "tú": "you (informal)",
    "nosotros": "we",
    "nosotras": "we (fem.)",
    "ellos": "they",
    "ellas": "they (fem.)",
    "ustedes": "you all",
    "mi": "my",
    "mis": "my (plural)",
    "su": "his / her / their / your",
    "sus": "his / her / their / your (plural)",
    "tu": "your (possessive)",
    "tus": "your (possessive plural)",
    "esto": "this (neutral)",
    "este": "this (masc.)",
    "esta": "this (fem.)",
    "ese": "that (masc.)",
    "esa": "that (fem.)",
    "algo": "something",
    "todo": "everything / all",
    "todas": "all (fem. plural)",
    "todos": "all (masc. plural)",

    
    "es": "is",
    "soy": "I am",
    "eres": "you are",
    "somos": "we are",
    "son": "they are / you all are",
    "estoy": "I am (state/location)",
    "está": "is / you are (formal)",
    "estás": "you are (informal)",
    "estamos": "we are (state/location)",
    "están": "they are / you all are (state/location)",
    "fue": "was / went (past)",
    "era": "was (descriptive past)",
    "quiero": "I want",
    "quiere": "he / she wants",
    "queremos": "we want",
    "quieren": "they want / you all want",
    "necesito": "I need",
    "necesita": "he / she needs",
    "necesitamos": "we need",
    "necesitan": "they need",
    "tengo": "I have",
    "tiene": "he / she has",
    "tenemos": "we have",
    "tienen": "they have",
    "hambre": "hunger (as in 'tengo hambre')",
    "gusta": "likes / pleasing to",
    "gustan": "they like / pleasing to (plural)",
    "gustaría": "would like",
    "me gustaría": "I would like",
    "vivo": "I live",
    "viven": "they live",
    "trabaja": "he / she works",
    "trabajando": "working",
    "estudiando": "studying",
    "aprendiendo": "learning",
    "arreglando": "fixing",
    "leyendo": "reading",
    "viviendo": "living",
    "esperando": "waiting",
    "viendo": "watching / seeing",
    "hablando": "talking / speaking",
    "cocinando": "cooking",
    "conduciendo": "driving",
    "planeando": "planning",
    "desayunando": "eating breakfast",
    "llega": "arrives / he or she arrives",
    "llegamos": "we arrived",
    "llegarán": "they will arrive",
    "llegue": "I arrive / he or she arrives (subjunctive)",
    "abre": "opens",
    "sugirió": "suggested",
    "argumentaron": "argued",
    "terminaron": "they finished",
    "insistió": "insisted",
    "explicó": "explained",
    "pidió": "asked for / requested",
    "ayudara": "helped / would help (subjunctive)",
    "planean": "they plan",
    "adaptarnos": "to adapt ourselves",
    "prepararnos": "to prepare ourselves",
    "tendrá": "he / she will have",
    "serán": "they will be",
    "completó": "completed",
    "visitó": "visited",
    "olvidó": "forgot",
    "llamó": "called",
    "compré": "I bought",
    "limpié": "I cleaned",
    "escribí": "I wrote",
    "estudiaré": "I will study",
    "ayudaré": "I will help",
    "continuaremos": "we will continue",
    "comeremos": "we will eat",
    "irnos": "to leave / to go away",

    
    "hoy": "today",
    "mañana": "tomorrow / morning",
    "ayer": "yesterday",
    "anoche": "last night",
    "ahora": "now",
    "siempre": "always",
    "nunca": "never",
    "ya": "already / now",
    "todavía": "still / yet",
    "normalmente": "normally",
    "pronto": "soon",
    "tarde": "late / afternoon",
    "temprano": "early",
    "a menudo": "often",
    "más tarde": "later",
    "esta noche": "tonight",
    "a las nueve": "at nine",
    "claramente": "clearly",
    "lentamente": "slowly",
     
    "bueno": "good",
    "buena": "good (fem.)",
    "buenos": "good (plural)",
    "buenas": "good (fem. plural)",
    "malo": "bad",
    "mala": "bad (fem.)",
    "malos": "bad (plural)",
    "malas": "bad (fem. plural)",
    "nuevo": "new",
    "nueva": "new (fem.)",
    "nuevos": "new (plural)",
    "nuevas": "new (fem. plural)",
    "pequeño": "small",
    "pequeña": "small (fem.)",
    "pequeños": "small (plural)",
    "pequeña_plural": "small (fem. plural)",
    "caliente": "hot",
    "calientes": "hot (plural)",
    "frío": "cold",
    "fría": "cold (fem.)",
    "fríos": "cold (plural)",
    "frías": "cold (fem. plural)",
    "feliz": "happy",
    "felices": "happy (plural)",
    "difícil": "difficult",
    "difíciles": "difficult (plural)",
    "fácil": "easy",
    "fáciles": "easy (plural)",
    "clara": "clear / bright (fem.)",
    "claro": "clear / bright (masc.)",
    "claros": "clear (plural)",
    "claras": "clear (fem. plural)",
    "grande": "big / large",
    "grandes": "big / large (plural)",
    "alto": "tall / high",
    "alta": "tall (fem.)",
    "altos": "tall (plural)",
    "altas": "tall (fem. plural)",
    "deliciosa": "delicious (fem.)",
    "delicioso": "delicious (masc.)",
    "amable": "kind / nice",
    "amables": "kind / nice (plural)",
    "limpia": "clean (fem.)",
    "limpio": "clean (masc.)",
    "roja": "red (fem.)",
    "rojo": "red (masc.)",
    "retrasado": "delayed / late",
    "retrasada": "delayed (fem.)",
    "realista": "realistic",
    "realistas": "realistic (plural)",
    "profesional": "professional",
    "profesionales": "professional (plural)",
    "innovadora": "innovative (fem.)",
    "innovador": "innovative (masc.)",
    "innecesarios": "unnecessary (plural)",
    "innecesario": "unnecessary",
    "arriesgada": "risky (fem.)",
    "arriesgado": "risky (masc.)",
    "capaz": "capable",
    "capaces": "capable (plural)",
    "efectivo": "effective",
    "efectiva": "effective (fem.)",
    "positivo": "positive",
    "positiva": "positive (fem.)",
    "positivos": "positive (plural)",
    "complicado": "complicated",
    "complicada": "complicated (fem.)",
    "importante": "important",
    "importantes": "important (plural)",
    "diferente": "different",
    "diferentes": "different (plural)",
    "mejor": "better",
    "mejores": "better / best (plural)",
    "excelente": "excellent",
    "excelentes": "excellent (plural)",
    "posible": "possible",
    "posibles": "possible (plural)",
    "próximo": "next",
    "próxima": "next (fem.)",

    
    "once": "eleven",
    "doce": "twelve",
    "trece": "thirteen",
    "catorce": "fourteen",
    "quince": "fifteen",
    "dieisiete": "sixteen",
    "diecisiete": "seventeen",
    "dieciocho": "eighteen",
    "diecinueve": "nineteen",
    "veinte": "twenty"
};  
