export default {
    A1: [
        { english: "Hello, how are you?", dutch: "hallo hoe gaat het" },
        { english: "Good morning, sir.", dutch: "goedemorgen meneer" },
        { english: "Good afternoon, ma'am.", dutch: "goedemiddag mevrouw" },
        { english: "Good night, family.", dutch: "goede nacht familie" },
        { english: "Goodbye, my friend.", dutch: "tot ziens mijn vriend" },
        { english: "I am very happy today.", dutch: "ik ben heel gelukkig vandaag" },
        { english: "How is he?", dutch: "hoe is het met hem" },
        { english: "How is she?", dutch: "hoe is het met haar" },
        { english: "Hello, good morning.", dutch: "hallo goedemorgen" },
        { english: "Goodbye, sir.", dutch: "tot ziens meneer" },

        { english: "I would like water, please.", dutch: "ik wil graag water alstublieft" },
        { english: "I would like beer, please.", dutch: "ik wil graag bier alstublieft" },
        { english: "Where is the bathroom?", dutch: "waar is de badkamer" },
        { english: "Where is the hotel?", dutch: "waar is het hotel" },
        { english: "The hotel is near.", dutch: "het hotel is dichtbij" },
        { english: "Where is the station?", dutch: "waar is het station" },
        { english: "Where is the train?", dutch: "waar is de trein" },
        { english: "Where is the bus?", dutch: "waar is de bus" },
        { english: "Where is the airport?", dutch: "waar is de luchthaven" },
        { english: "Where is the ticket?", dutch: "waar is het kaartje" },

        { english: "I want a coffee.", dutch: "ik wil een koffie" },
        { english: "The coffee is hot.", dutch: "de koffie is heet" },
        { english: "I want to study more.", dutch: "meer studeren" },
        { english: "I want to work more.", dutch: "meer werken" },
        { english: "I want to read books.", dutch: "boeken lezen" },
        { english: "I want to write books.", dutch: "boeken schrijven" },
        { english: "I want to go home.", dutch: "naar huis gaan" },
        { english: "I want to rest.", dutch: "uitrusten" },
        { english: "I want to clean the house.", dutch: "huis schoonmaken" },
        { english: "I want to cook today.", dutch: "vandaag koken" },
        { english: "I am learning.", dutch: "ik leer" },
        { english: "He is fixing the television.", dutch: "hij maakt de televisie te maken" },
        { english: "We are ready.", dutch: "wij zijn klaar" },
        { english: "The hour is near.", dutch: "het uur is nabij" },

        { english: "She is my sister.", dutch: "zij is mijn zus" },
        { english: "I have two brothers.", dutch: "ik heb twee broers" },
        { english: "My friend is very happy.", dutch: "mijn vriend is erg blij" },
        { english: "We have hunger.", dutch: "wij hebben honger" },
        { english: "They have a big house.", dutch: "zij hebben een groot huis" },
        { english: "The food is good.", dutch: "het eten is goed" },
        { english: "I want bread and milk.", dutch: "ik wil brood en melk" },
        { english: "Steak with french fries, please.", dutch: "biefstuk met friet alstublieft" },
        { english: "Rice without beans.", dutch: "rijst zonder bonen" },
        { english: "I like cold tea.", dutch: "koude thee vind ik lekker" },
        { english: "They like cheese and eggs.", dutch: "zij houden van kaas en eieren" },
        { english: "We like this place.", dutch: "wij vinden deze plek leuk" }
    ],

    A2: [
        { english: "Normally I get up early.", dutch: "normaal sta ik vroeg op" },
        { english: "I want to cook dinner now.", dutch: "ik wil nu avondeten koken" },
        { english: "She is learning fast now.", dutch: "zij leert nu snel" },
        { english: "He wants to finish homework early.", dutch: "hij wil huiswerk vroeg afmaken" },
        { english: "They want information now.", dutch: "zij willen nu informatie" },
        { english: "The movie finishes in ten minutes.", dutch: "de film eindigt over tien minuten" },
        { english: "I have fifteen minutes now.", dutch: "ik heb nu vijftien minuten" },
        { english: "Anoche I was happy.", dutch: "gisteravond was ik blij" },
        { english: "Before, I want breakfast.", dutch: "vooraf wil ik ontbijt" },
        { english: "She already finished homework.", dutch: "zij heeft het huiswerk al afgemaakt" },
        { english: "I still have problems.", dutch: "ik heb nog steeds problemen" },

        { english: "The kitchen is clean now.", dutch: "de keuken is nu schoon" },
        { english: "Open the kitchen window, please.", dutch: "open het keukenraam alstublieft" },
        { english: "I want to try a new breakfast today.", dutch: "ik wil vandaag een nieuw ontbijt proberen" },
        { english: "I want to fix the window now.", dutch: "ik wil het raam nu repareren" },
        { english: "He is fixing the television in the house.", dutch: "hij repareert de televisie in het huis" },
        { english: "We have food for lunch and dinner.", dutch: "wij hebben eten voor de lunch en het avondeten" },

        { english: "We want to visit parents today.", dutch: "vandaag ouders bezoeken" },
        { english: "Where is my friend? I want to wait.", dutch: "waar is mijn vriend ik wil wachten" },
        { english: "I want to drive to the airport.", dutch: "naar de luchthaven rijden" },

        { english: "I want to read the message now.", dutch: "ik wil het bericht nu lezen" },
        { english: "She wants to write a message.", dutch: "zij wil een bericht schrijven" },
        { english: "He wants more information, please.", dutch: "hij wil meer informatie alstublieft" },
        { english: "Don't forget the message.", dutch: "vergeet het bericht niet" },

        { english: "Where is the plane? It is late.", dutch: "waar is het vliegtuig het is laat" },
        { english: "The plane arrives in twenty minutes.", dutch: "het vliegtuig arriveert over twintig minuten" },
        { english: "I need transport to the station.", dutch: "ik heb vervoer naar het station nodig" },
        { english: "They want to leave the hotel early.", dutch: "zij willen het hotel vroeg verlaten" },
        { english: "We arrived near the new place.", dutch: "wij kwamen vlakbij de nieuwe plek aan" },
        { english: "I want new shoes for the trip.", dutch: "ik wil nieuwe schoenen voor de reis" },
        { english: "She likes her small shoes.", dutch: "zij houdt van haar kleine schoenen" },
        { english: "Often, he likes this clean house.", dutch: "hij houdt vaak van dit schone huis" },

        { english: "I have eleven new books.", dutch: "ik heb elf nieuwe boeken" },
        { english: "There are twelve buses in the station.", dutch: "er zijn twaalf bussen op het station" },
        { english: "Thirteen minutes to finish.", dutch: "dertig minuten om te eindigen" },
        { english: "Fourteen fish and rice, please.", dutch: "veertien vis en rijst alstublieft" },
        { english: "We have fifteen eggs for breakfast.", dutch: "wij hebben vijftien eieren voor het ontbijt" },
        { english: "She has sixteen apples.", dutch: "zij heeft zestien appels" },
        { english: "Seventeen train tickets, please.", dutch: "zeventien treinkaartjes alstublieft" },
        { english: "Eighteen beers for the house.", dutch: "achttien bieren voor het huis" },
        { english: "Nineteen people study here.", dutch: "negentien mensen studeren hier" },
        { english: "Twenty minutes to rest.", dutch: "twintig minuten om uit te rusten" }
    ],

    B1: [
        { english: "I have been here for a month.", dutch: "ik ben hier al een maand" },
        { english: "You have learned fast during the trip.", dutch: "je hebt snel geleerd tijdens de reis" },
        { english: "He has worked hard today.", dutch: "hij heeft vandaag hard gewerkt" },
        { english: "We have studied the past experiences.", dutch: "wij hebben de ervaringen uit het verleden bestudeerd" },
        { english: "They have lived here for two years.", dutch: "zij wonen hier al twee jaar" },
        { english: "She is working in the kitchen now.", dutch: "zij werkt nu in de keuken" },
        { english: "We are studying to improve our skills.", dutch: "wij studeren om onze vaardigheden te verbeteren" },
        { english: "He is reading a new book while waiting.", dutch: "hij leest een nieuw boek terwijl hij wacht" },
        { english: "They are living in a small place near school.", dutch: "zij wonen in een kleine plaats vlakbij de school" },

        { english: "I want to improve my communication skills.", dutch: "ik wil mijn communicatieve vaardigheden verbeteren" },
        { english: "We need to continue the conversations today.", dutch: "wij moeten de gesprekken vandaag voortzetten" },
        { english: "I want to understand the past experiences.", dutch: "ik wil de ervaringen uit het verleden begrijpen" },
        { english: "She wants to review the information now.", dutch: "zij wil de informatie nu beoordelen" },
        { english: "He needs to prepare the daily homework.", dutch: "hij moet het dagelijkse huiswerk voorbereiden" },
        { english: "They want to follow the rules after lunch.", dutch: "zij willen de regels na de lunch volgen" },
        { english: "I want to get a ticket for the trip.", dutch: "ik wil een kaartje voor de reis bemachtigen" },
        { english: "We need to change the daily routine.", dutch: "wij moeten de dagelijkse routine veranderen" },
        { english: "However, I understand your problems.", dutch: "toch begrijp ik jouw problemen" },

        { english: "Where is the new restaurant?", dutch: "waar is het nieuwe restaurant" },
        { english: "Bring the menu, please.", dutch: "breng het menu alstublieft" },
        { english: "Bring the bill to the table, please.", dutch: "breng de rekening naar de tafel alstublieft" },
        { english: "The bill is big after dinner.", dutch: "de rekening is groot na het avondeten" },
        { english: "I want to understand the restaurant menu.", dutch: "ik wil het restaurantmenu begrijpen" },

        { english: "I want to plan a new trip.", dutch: "ik wil een nieuwe reis plannen" },
        { english: "They want to find a hotel near the station.", dutch: "zij willen een hotel vlakbij het station vinden" },
        { english: "She needs to cancel her train ticket.", dutch: "zij moet haar treinkaartje annuleren" },
        { english: "He wants to bring his parents on the trip.", dutch: "hij wil zijn ouders meenemen op de reis" },
        { english: "We plan to move house this month.", dutch: "wij zijn van plan om deze maand te verhuizen" },
        { english: "They want to join our trip today.", dutch: "zij willen zich vandaag bij onze reis aansluiten" },
        { english: "Where can I find transport now?", dutch: "waar kan ik nu vervoer vinden" },
        { english: "The plane was canceled last night.", dutch: "het vliegtuig werd gisteravond geannuleerd" },

        { english: "He studied for an hour during lunch.", dutch: "hij studeerde een uur tijdens de lunch" },
        { english: "She has been working here for a month.", dutch: "zij werkt hier al een maand" },
        { english: "They have lived in this house for ten years.", dutch: "zij wonen al tien jaar in dit huis" },
        { english: "I need to review everything after this month.", dutch: "ik moet alles na deze maand bekijken" },
        { english: "We want to prepare the trip during the month.", dutch: "wij willen de reis gedurende de maand voorbereiden" },
        { english: "He has learned a lot about skills this year.", dutch: "hij heeft dit jaar veel geleerd over vaardigheden" },
        { english: "She wants to get information about the hotel before.", dutch: "zij wil vooraf informatie over het hotel krijgen" },
        { english: "They will continue studying after two years.", dutch: "zij zullen na twee jaar doorgaan met studeren" },
        { english: "While studying, I want to improve daily.", dutch: "tijdens het studeren wil ik dagelijks verbeteren" }
    ],

    B2: [
        { english: "They want to analyze the situation.", dutch: "zij willen de situatie analyseren" },
        { english: "We need to evaluate the risks carefully.", dutch: "wij moeten de risico's zorgvuldig evalueren" },
        { english: "Although it was difficult, she finished the task.", dutch: "hoewel het moeilijk was, heeft zij de taak afgemaakt" },
        { english: "They argued that the plan was not realistic.", dutch: "zij beargumenteerden dat het plan niet realistisch was" },
        { english: "The strategy has increased our performance results.", dutch: "de strategie heeft onze prestatieresultaten verhoogd" },
        { english: "Therefore, it is necessary to analyze the risk concept.", dutch: "daarom is het noodzakelijk om het risicoconcept te analyseren" },
        { english: "We need to coordinate a positive strategy to achieve results.", dutch: "wij moeten een positieve strategie coördineren om resultaten te behalen" },
        { english: "She has clarified her innovative approach during the discussion.", dutch: "zij heeft haar vernieuwende aanpak tijdens de discussie verduidelijkt" },
        { english: "I want to update the system to strengthen our skills.", dutch: "ik wil het systeem bijwerken om onze vaardigheden te versterken" },
        { english: "He has explored every possibility to optimize the task.", dutch: "hij heeft elke mogelijkheid onderzocht om de taak te optimaliseren" },
        { english: "They argued that a professional approach is necessary.", dutch: "zij hebben aangevoerd dat een professionele aanpak noodzakelijk is" },
        { english: "We have analyzed the complicated situation again.", dutch: "wij hebben de ingewikkelde situatie opnieuw geanalyseerd" },
        { english: "She has adapted the strategy to improve performance.", dutch: "zij heeft de strategie aangepast om de prestaties te verbeteren" },
        { english: "I want to try a positive approach now.", dutch: "ik wil nu een positieve aanpak proberen" },
        { english: "He forgot to check the results of the process.", dutch: "hij vergat de resultaten van het proces te controleren" },
        { english: "We must analyze the results carefully.", dutch: "wij moeten de resultaten zorgvuldig analyseren" },
        { english: "She wants to improve her performance.", dutch: "zij wil haar prestaties verbeteren" },
        { english: "We need to update the system.", dutch: "wij moeten het systeem bijwerken" },
        { english: "He explained the strategy clearly.", dutch: "hij legde de strategie helder uit" },
        { english: "They want to optimize the process.", dutch: "zij willen het proces optimaliseren" },

        { english: "We will continue even if there are challenges.", dutch: "wij gaan door zelfs als er uitdagingen zijn" },
        { english: "Despite the problems, they finished the trip.", dutch: "ondanks de problemen hebben zij de reis afgemaakt" },
        { english: "We need to adapt to the new situation.", dutch: "wij moeten ons aanpassen aan de nieuwe situatie" },
        { english: "She wants to expand her professional experience.", dutch: "zij wil haar professionele ervaring uitbreiden" },
        { english: "He insisted on reviewing the data again.", dutch: "hij stond erop de gegevens opnieuw te bekijken" },
        { english: "They hope to achieve better results.", dutch: "zij hopen betere resultaten te behalen" },
        { english: "We need to clarify the instructions.", dutch: "wij moeten de instructies verduidelijken" },
        { english: "Although it seems easy, it is complicated.", dutch: "hoewel het makkelijk lijkt, is het ingewikkeld" },
        { english: "She argued that the change was necessary.", dutch: "zij betoogde dat de verandering noodzakelijk was" },
        { english: "They want to strengthen the communication process.", dutch: "zij willen het communicatieproces versterken" },
        { english: "They discussed the situation for an hour during lunch.", dutch: "zij hebben tijdens de lunch een uur over de situatie gediscussieerd" },
        { english: "She wants to learn about our society and culture.", dutch: "zij wil over onze maatschappij en cultuur leren" },
        { english: "In addition, motivation is necessary to achieve goals.", dutch: "bovendien is motivatie noodzakelijk om doelen te bereiken" },
        { english: "Expectations are high for the future long term trip.", dutch: "de verwachtingen zijn hooggespannen voor de toekomstige langetermijnreis" },
        { english: "They live in a remote place, however they study daily.", dutch: "zij wonen op een afgelegen plek, toch studeren zij dagelijks" },

        { english: "I want to understand this abstract concept better.", dutch: "ik wil dit abstracte concept beter begrijpen" },
        { english: "We must prepare for possible system changes.", dutch: "wij moeten ons voorbereiden op mogelijke systeemwijzigingen" },
        { english: "They want to increase information access in society.", dutch: "zij willen de informatietoegang in de samenleving vergroten" },
        { english: "He has reduced the risk of the strategy.", dutch: "hij heeft het risico van de strategie verkleind" }
    ],

    C1: [
        { english: "Consequently, the implementation requires a comprehensive overview.", dutch: "bijgevolg vereist de implementatie een uitgebreid overzicht" },
        { english: "She emphasized the significance of sustainable development.", dutch: "zij benadrukte het belang van duurzame ontwikkeling" },
        { english: "We must scrutinize the underlying assumptions of the model.", dutch: "wij moeten de onderliggende aannames van het model nauwkeurig onderzoeken" },
        { english: "The phenomenon has triggered widespread academic debate.", dutch: "het fenomeen heeft een breed academisch debat op losse schroeven gezet" },
        { english: "He articulated a compelling vision for structural reform.", dutch: "hij formuleerde een meeslepende visie voor structurele hervormingen" },
        { english: "They advocate for a paradigm shift in economic policy.", dutch: "zij pleiten voor een paradigmaverschuiving in het economisch beleid" },
        { english: "Subsequent analyses revealed discrepancies in the dataset.", dutch: "latere analyses brachten discrepanties in de dataset aan het licht" },
        { english: "The committee endorsed the overarching strategic framework.", dutch: "het comité onderschreef het algehele strategische kader" },
        { english: "Her meticulous research shed light on the anomaly.", dutch: "haar zorgvuldige onderzoek wierp licht op de anomalie" },
        { english: "We need to mitigate potential vulnerabilities in the infrastructure.", dutch: "wij moeten potentiële kwetsbaarheden in de infrastructuur beperken" }
    ],

    C2: [
        { english: "The erstwhile policy proved antithetical to long-term growth.", dutch: "het voormalige beleid bleek haaks te staan op de groei op lange termijn" },
        { english: "His polemical discourse obfuscated the core tenets of the argument.", dutch: "zijn polemische betoog vertroebelde de kernprincipes van het argument" },
        { english: "We encountered an intractable conundrum during the synthesis phase.", dutch: "wij stuitten op een onoplosbaar raadsel tijdens de synthesefase" },
        { english: "The labyrinthine bureaucracy impeded expedient resolutions.", dutch: "de labyrintische bureaucratie belemmerde snelle oplossingen" },
        { english: "She demonstrated consummate skill in her rhetorical delivery.", dutch: "zij toonde volmaakte vaardigheid in haar retorische presentatie" },
        { english: "The ephemeral nature of the trend defies rigorous quantification.", dutch: "het efemere karakter van de trend laat zich niet streng kwantificeren" },
        { english: "They sought to ameliorate the pernicious effects of the crisis.", dutch: "zij trachtten de verderfelijke gevolgen van de crisis te verzachten" },
        { english: "His idiosyncratic methodology yielded unorthodox conclusions.", dutch: "zijn idiosyncratische methodologie leverde onorthodoxe conclusies op" },
        { english: "The salient details were obscured by superfluous rhetoric.", dutch: "de opvallende details werden verdoezeld door overbodige retoriek" },
        { english: "An overarching synthesis is paramount for cohesive interpretation.", dutch: "een alomvattende synthese is van het grootste belang voor een samenhangende interpretatie" }
    ]
};