export default {
    "hoe gaat het": "how are you",
    "waar woon je": "where do you live",
    "hoe laat is het": "what time is it",
    "vind je koffie lekker": "you like coffee",
    "ik hou van muziek": "I like music",
    "ik woon in de stad": "I live in the city",
    "ik werk in een hotel": "I work in a hotel",
    "ik wil eten": "I want to eat",
    "ik wil drinken": "I want to drink",
    "waar is de badkamer": "where is the bathroom",
    "zij rent snel": "she runs fast",
    "zij is snel": "she is fast",
    "zij gaat snel": "she goes fast",

    "wat heb je gisteren gedaan": "what did you do yesterday",
    "ben je naar de supermarkt gegaan": "did you go to the supermarket",
    "reis je vaak": "you travel often",
    "wat heb je gekocht": "what did you buy",
    "wat ben je aan het doen": "what are you doing",
    "eet je meestal vroeg": "you usually eat early",
    "ik heb hulp nodig": "I need help",
    "ik wil een reservering maken": "I want to make a reservation",
    "waar is het station": "where is the station",

    "ik ben Spaans aan het leren": "I have been learning Spanish",
    "ik geniet van reizen": "I enjoy traveling",
    "ik wil mijn vaardigheden verbeteren": "I want to improve my skills",
    "wat vind je van de stad": "what do you think of the city",
    "hoe behoud je een gezonde levensstijl": "how do you maintain a healthy life",
    "wat heb je recentelijk geleerd": "what did you learn recently",
    "wat zijn je doelen": "what are your goals",
    "welke ervaringen uit het verleden heb je": "what past experiences do you have",

    "hoe ga je om met stressvolle situaties": "how do you handle stressful situations",
    "wat is jouw mening over technologie": "what is your opinion on technology",
    "hoe is je leven veranderd": "how has your life changed",
    "welke uitdagingen sta je te wachten": "what challenges do you face",
    "wat hoop je te bereiken": "what do you hope to achieve",
    "wat denk je over de toekomst": "what do you think about the future",
    "hoe zie je de huidige samenleving": "how do you see modern society",
    "wat is jouw perspectief": "what is your perspective"
};