export default {
    A1: [
        { dutch: "leven", english: "to live", category: "Daily Life" },
        { dutch: "werken", english: "to work", category: "Daily Life" },
        { dutch: "studeren", english: "to study", category: "Daily Life" },
        { dutch: "lezen", english: "to read", category: "Daily Life" },
        { dutch: "boeken", english: "books", category: "Daily Life" },
        { dutch: "uur", english: "hour", category: "Daily Life" },
        { dutch: "opstaan", english: "to get up", category: "Daily Life" },
        { dutch: "muziek", english: "music", category: "Daily Life" },
        { dutch: "televisie", english: "television", category: "Daily Life" },
        { dutch: "schoonmaken", english: "to clean", category: "Daily Life" },
        { dutch: "koken", english: "to cook", category: "Daily Life" },
        { dutch: "openen", english: "to open", category: "Daily Life" },
        { dutch: "beëindigen", english: "to finish", category: "Daily Life" },
        { dutch: "schrijven", english: "to write", category: "Daily Life" },
        { dutch: "leren", english: "to learn", category: "Daily Life" },
        { dutch: "gaan", english: "to go", category: "Daily Life" },
        { dutch: "doen", english: "to do", category: "Daily Life" },
        { dutch: "zien", english: "to see", category: "Daily Life" },
        { dutch: "luisteren", english: "to listen", category: "Daily Life" },
        { dutch: "uitgaan", english: "to go out", category: "Daily Life" },
        { dutch: "rusten", english: "to rest", category: "Daily Life" },
        { dutch: "heet", english: "hot", category: "Daily Life" },
        { dutch: "koud", english: "cold", category: "Daily Life" },
        { dutch: "gelukkig", english: "happy", category: "Daily Life" },
        { dutch: "nieuw", english: "new", category: "Daily Life" },
        { dutch: "hallo", english: "hello", category: "Daily Life" },
        { dutch: "tot ziens", english: "goodbye", category: "Daily Life" },
        { dutch: "dank je", english: "thank you", category: "Daily Life" },
        { dutch: "het spijt me", english: "sorry / I feel", category: "Daily Life" },
        { dutch: "je bent", english: "you are", category: "Daily Life" },
        { dutch: "klaar", english: "ready", category: "Daily Life" },
        { dutch: "wakker", english: "awake", category: "Daily Life" },
        { dutch: "tijd", english: "time", category: "Daily Life" },
        { dutch: "problemen", english: "problems", category: "Daily Life" },
        { dutch: "verandering", english: "change", category: "Daily Life" },
        { dutch: "goedemorgen", english: "good morning", category: "Daily Life" },
        { dutch: "goedemiddag", english: "good afternoon", category: "Daily Life" },
        { dutch: "goedenavond", english: "good night", category: "Daily Life" },
        { dutch: "goed", english: "well / good", category: "Daily Life" },
        { dutch: "meneer", english: "sir", category: "Daily Life" },
        { dutch: "mevrouw", english: "ma'am", category: "Daily Life" },

        { dutch: "familie", english: "family", category: "Family" },
        { dutch: "moeder", english: "mother", category: "Family" },
        { dutch: "vader", english: "father", category: "Family" },
        { dutch: "zoon", english: "son", category: "Family" },
        { dutch: "dochter", english: "daughter", category: "Family" },
        { dutch: "vriend", english: "friend", category: "Family" },
        { dutch: "vriendin", english: "friend (female)", category: "Family" },
        { dutch: "zus", english: "sister", category: "Family" },
        { dutch: "broers", english: "brothers", category: "Family" },
        { dutch: "zussen", english: "sisters", category: "Family" },
        { dutch: "oma", english: "grandmother", category: "Family" },
        { dutch: "honger", english: "hunger", category: "Family" },
        { dutch: "we hebben", english: "we have", category: "Family" },
        { dutch: "ze hebben", english: "they have", category: "Family" },

        { dutch: "water", english: "water", category: "Food & Drink" },
        { dutch: "eten", english: "food", category: "Food & Drink" },
        { dutch: "koffie", english: "coffee", category: "Food & Drink" },
        { dutch: "thee", english: "tea", category: "Food & Drink" },
        { dutch: "melk", english: "milk", category: "Food & Drink" },
        { dutch: "biefstuk", english: "steak", category: "Food & Drink" },
        { dutch: "frietjes", english: "french fries", category: "Food & Drink" },
        { dutch: "brood", english: "bread", category: "Food & Drink" },
        { dutch: "bier", english: "beer", category: "Food & Drink" },
        { dutch: "ei", english: "egg", category: "Food & Drink" },
        { dutch: "fruit", english: "fruit", category: "Food & Drink" },
        { dutch: "appel", english: "apple", category: "Food & Drink" },
        { dutch: "sinaasappel", english: "orange", category: "Food & Drink" },
        { dutch: "banaan", english: "banana", category: "Food & Drink" },
        { dutch: "kip", english: "chicken", category: "Food & Drink" },
        { dutch: "vis", english: "fish", category: "Food & Drink" },
        { dutch: "soep", english: "soup", category: "Food & Drink" },
        { dutch: "salade", english: "salad", category: "Food & Drink" },
        { dutch: "rijst", english: "rice", category: "Food & Drink" },
        { dutch: "bonen", english: "beans", category: "Food & Drink" },
        { dutch: "kaas", english: "cheese", category: "Food & Drink" },
        { dutch: "zout", english: "salt", category: "Food & Drink" },

        { dutch: "bus", english: "bus", category: "Travel" },
        { dutch: "trein", english: "train", category: "Travel" },
        { dutch: "kaartje", english: "ticket", category: "Travel" },
        { dutch: "station", english: "station", category: "Travel" },
        { dutch: "luchthaven", english: "airport", category: "Travel" },
        { dutch: "huis", english: "house", category: "Travel" },
        { dutch: "school", english: "school", category: "Travel" },
        { dutch: "hotel", english: "hotel", category: "Travel" },
        { dutch: "badkamer", english: "bathroom", category: "Travel" },
        { dutch: "plaats", english: "place", category: "Travel" },

        { dutch: "en", english: "and", category: "Connectors" },
        { dutch: "of", english: "or", category: "Connectors" },
        { dutch: "met", english: "with", category: "Connectors" },
        { dutch: "zonder", english: "without", category: "Connectors" },
        { dutch: "meer", english: "more", category: "Connectors" },
        { dutch: "weinig", english: "little", category: "Connectors" },
        { dutch: "alleen", english: "only", category: "Connectors" },
        { dutch: "zeer", english: "very", category: "Connectors" },
        { dutch: "dichtbij", english: "near", category: "Connectors" },
        { dutch: "voor", english: "for", category: "Connectors" },
        { dutch: "naar", english: "to", category: "Connectors" },
        { dutch: "in", english: "in", category: "Connectors" },
        { dutch: "zij", english: "she", category: "Connectors" },
        { dutch: "hij", english: "he", category: "Connectors" },
        { dutch: "zij", english: "they", category: "Connectors" },
        { dutch: "zijn / haar / hun", english: "his / her / their", category: "Connectors" },
        { dutch: "wat", english: "what", category: "Connectors" },
        { dutch: "wie", english: "who", category: "Connectors" },
        { dutch: "wanneer", english: "when", category: "Connectors" },
        { dutch: "hoe", english: "how", category: "Connectors" },
        { dutch: "welke", english: "which", category: "Connectors" },
        { dutch: "waar", english: "where", category: "Connectors" },
        { dutch: "nee", english: "no / not", category: "Connectors" },
        { dutch: "ja", english: "yes", category: "Connectors" },
        { dutch: "er is / er zijn", english: "there is / there are", category: "Connectors" },
        { dutch: "andere", english: "other / another", category: "Connectors" },
        { dutch: "ondanks", english: "despite", category: "Connectors" },
        { dutch: "alstublieft", english: "please", category: "Connectors" },
        { dutch: "mij", english: "myself / to me", category: "Connectors" },
        { dutch: "mijn", english: "my", category: "Connectors" },
        { dutch: "een", english: "a / an (masculine)", category: "Connectors" },
        { dutch: "een", english: "a / an (feminine)", category: "Connectors" },
        { dutch: "de", english: "the (masculine)", category: "Connectors" },
        { dutch: "de", english: "the (feminine)", category: "Connectors" },

        { dutch: "is", english: "is", category: "Verbs" },
        { dutch: "vindt leuk", english: "likes", category: "Verbs" },
        { dutch: "vinden leuk", english: "they like", category: "Verbs" },
        { dutch: "zou willen", english: "would like", category: "Verbs" },
        { dutch: "lerend", english: "learning", category: "Verbs" },
        { dutch: "reparerend", english: "fixing", category: "Verbs" },
        { dutch: "is", english: "is / you are (formal)", category: "Verbs" },
        { dutch: "ik wil", english: "I want", category: "Verbs" },
        { dutch: "ik heb", english: "I have", category: "Verbs" },
        { dutch: "ik heb nodig", english: "I need", category: "Verbs" },

        { dutch: "goed", english: "good", category: "Adjectives" },
        { dutch: "moeilijk", english: "difficult", category: "Adjectives" },
        { dutch: "helder", english: "clear", category: "Adjectives" },
        { dutch: "gemakkelijk", english: "easy", category: "Adjectives" },
        { dutch: "slecht", english: "bad", category: "Adjectives" },
        { dutch: "klein", english: "small", category: "Adjectives" },

        { dutch: "één", english: "one", category: "Numbers" },
        { dutch: "twee", english: "two", category: "Numbers" },
        { dutch: "drie", english: "three", category: "Numbers" },
        { dutch: "vier", english: "four", category: "Numbers" },
        { dutch: "vijf", english: "five", category: "Numbers" },
        { dutch: "zes", english: "six", category: "Numbers" },
        { dutch: "zeven", english: "seven", category: "Numbers" },
        { dutch: "acht", english: "eight", category: "Numbers" },
        { dutch: "negen", english: "nine", category: "Numbers" },
        { dutch: "tien", english: "ten", category: "Numbers" }
    ],

    A2: [
        { dutch: "ontbijt", english: "breakfast", category: "Daily Life" },
        { dutch: "lunch", english: "lunch", category: "Daily Life" },
        { dutch: "avondeten", english: "dinner", category: "Daily Life" },
        { dutch: "vroeg", english: "early", category: "Daily Life" },
        { dutch: "laat", english: "late", category: "Daily Life" },
        { dutch: "gisteravond", english: "last night", category: "Daily Life" },
        { dutch: "nu", english: "now", category: "Daily Life" },
        { dutch: "minuten", english: "minutes", category: "Daily Life" },
        { dutch: "huiswerk", english: "homework", category: "Daily Life" },
        { dutch: "bericht", english: "message", category: "Daily Life" },
        { dutch: "informatie", english: "information", category: "Daily Life" },
        { dutch: "film", english: "movie", category: "Daily Life" },
        { dutch: "raam", english: "window", category: "Daily Life" },
        { dutch: "keuken", english: "kitchen", category: "Daily Life" },
        { dutch: "schoenen", english: "shoes", category: "Daily Life" },
        { dutch: "reis", english: "trip", category: "Daily Life" },
        { dutch: "proberen", english: "to try", category: "Daily Life" },
        { dutch: "vergeten", english: "to forget", category: "Daily Life" },
        { dutch: "wachten", english: "to wait", category: "Daily Life" },
        { dutch: "rijden", english: "to drive", category: "Daily Life" },
        { dutch: "repareren", english: "to fix", category: "Daily Life" },
        { dutch: "weggaan", english: "to leave", category: "Daily Life" },
        { dutch: "aankomen", english: "to arrive", category: "Daily Life" },

        { dutch: "ouders", english: "parents", category: "Family" },

        { dutch: "vliegtuig", english: "plane", category: "Travel" },
        { dutch: "bezoeken", english: "to visit", category: "Travel" },
        { dutch: "transport", english: "transport", category: "Travel" },

        { dutch: "regelmatig", english: "often", category: "Connectors" },
        { dutch: "voordat", english: "before", category: "Connectors" },
        { dutch: "al", english: "already", category: "Connectors" },
        { dutch: "nog", english: "still", category: "Connectors" },
        { dutch: "normaal gesproken", english: "normally", category: "Connectors" },
        { dutch: "omdat", english: "because", category: "Connectors" },

        { dutch: "elf", english: "eleven", category: "Numbers" },
        { dutch: "twaalf", english: "twelve", category: "Numbers" },
        { dutch: "dertien", english: "thirteen", category: "Numbers" },
        { dutch: "veertien", english: "fourteen", category: "Numbers" },
        { dutch: "vijftien", english: "fifteen", category: "Numbers" },
        { dutch: "zestien", english: "sixteen", category: "Numbers" },
        { dutch: "zeventien", english: "seventeen", category: "Numbers" },
        { dutch: "achttien", english: "eighteen", category: "Numbers" },
        { dutch: "negentien", english: "nineteen", category: "Numbers" },
        { dutch: "twintig", english: "twenty", category: "Numbers" }
    ],

    B1: [
        { dutch: "heb", english: "I have (auxiliary)", category: "Daily Life" },
        { dutch: "hebt", english: "you have (auxiliary)", category: "Daily Life" },
        { dutch: "heeft", english: "he/she has (auxiliary)", category: "Daily Life" },
        { dutch: "hebben", english: "we have (auxiliary)", category: "Daily Life" },
        { dutch: "hebben", english: "you (plural) have (auxiliary)", category: "Daily Life" },
        { dutch: "hebben", english: "they have (auxiliary)", category: "Daily Life" },

        { dutch: "geweest", english: "been", category: "Daily Life" },
        { dutch: "geleerd", english: "learned", category: "Daily Life" },
        { dutch: "aan het werk", english: "working", category: "Daily Life" },
        { dutch: "aan het studeren", english: "studying", category: "Daily Life" },
        { dutch: "aan het lezen", english: "reading", category: "Daily Life" },
        { dutch: "wonend", english: "living", category: "Daily Life" },
        { dutch: "dagelijks", english: "daily", category: "Daily Life" },

        { dutch: "communicatie", english: "communication", category: "Daily Life" },
        { dutch: "gesprekken", english: "conversations", category: "Daily Life" },
        { dutch: "verbeteren", english: "to improve", category: "Daily Life" },
        { dutch: "vaardigheden", english: "skills", category: "Daily Life" },
        { dutch: "beoordelen", english: "to review", category: "Daily Life" },
        { dutch: "doorgaan", english: "to continue", category: "Daily Life" },
        { dutch: "volgen", english: "to follow", category: "Daily Life" },
        { dutch: "voorbereiden", english: "to prepare", category: "Daily Life" },
        { dutch: "verkrijgen", english: "to get", category: "Daily Life" },
        { dutch: "begrijpen", english: "to understand", category: "Daily Life" },

        { dutch: "ervaringen", english: "experiences", category: "Family" },
        { dutch: "afgelopen", english: "past", category: "Family" },

        { dutch: "restaurant", english: "restaurant", category: "Food & Drink" },
        { dutch: "menu", english: "menu", category: "Food & Drink" },
        { dutch: "rekening", english: "bill", category: "Food & Drink" },

        { dutch: "vinden", english: "to find", category: "Travel" },
        { dutch: "annuleren", english: "to cancel", category: "Travel" },
        { dutch: "meebrengen", english: "to bring", category: "Travel" },
        { dutch: "plannen", english: "to plan", category: "Travel" },
        { dutch: "verhuizen", english: "to move (house)", category: "Travel" },
        { dutch: "zich aansluiten", english: "to join", category: "Travel" },

        { dutch: "terwijl", english: "while", category: "Connectors" },
        { dutch: "echter", english: "however", category: "Connectors" },
        { dutch: "over", english: "about", category: "Connectors" },
        { dutch: "na", english: "after", category: "Connectors" },
        { dutch: "tijdens", english: "during", category: "Connectors" },

        { dutch: "maand", english: "month", category: "Numbers" },
        { dutch: "jaar", english: "years", category: "Numbers" }
    ],
    B2: [
        { dutch: "proces", english: "process", category: "Daily Life" },
        { dutch: "resultaten", english: "results", category: "Daily Life" },
        { dutch: "prestatie", english: "performance", category: "Daily Life" },
        { dutch: "strategie", english: "strategy", category: "Daily Life" },
        { dutch: "systeem", english: "system", category: "Daily Life" },
        { dutch: "aanpak", english: "approach", category: "Daily Life" },
        { dutch: "concept", english: "concept", category: "Daily Life" },
        { dutch: "risico", english: "risk", category: "Daily Life" },
        { dutch: "mogelijkheid", english: "possibility", category: "Daily Life" },
        { dutch: "situatie", english: "situation", category: "Daily Life" },

        { dutch: "optimaliseren", english: "to optimize", category: "Daily Life" },
        { dutch: "coördineren", english: "to coordinate", category: "Daily Life" },
        { dutch: "verhogen", english: "to increase", category: "Daily Life" },
        { dutch: "bijwerken", english: "to update", category: "Daily Life" },
        { dutch: "analyseren", english: "to analyze", category: "Daily Life" },
        { dutch: "evalueren", english: "to evaluate", category: "Daily Life" },
        { dutch: "bespreken", english: "to discuss", category: "Daily Life" },
        { dutch: "verhelderen", english: "to clarify", category: "Daily Life" },
        { dutch: "versterken", english: "to strengthen", category: "Daily Life" },
        { dutch: "zich aanpassen", english: "to adapt", category: "Daily Life" },
        { dutch: "bereiken", english: "to achieve", category: "Daily Life" },

        { dutch: "ingewikkeld", english: "complicated", category: "Daily Life" },
        { dutch: "noodzakelijk", english: "necessary", category: "Daily Life" },
        { dutch: "mogelijk", english: "possible", category: "Daily Life" },
        { dutch: "effectief", english: "effective", category: "Daily Life" },
        { dutch: "realistisch", english: "realistic", category: "Daily Life" },
        { dutch: "innovatief", english: "innovative", category: "Daily Life" },
        { dutch: "professioneel", english: "professional", category: "Daily Life" },
        { dutch: "positief", english: "positive", category: "Daily Life" },

        { dutch: "geanalyseerd", english: "analyzed", category: "Daily Life" },
        { dutch: "geëvalueerd", english: "evaluated", category: "Daily Life" },
        { dutch: "beargumenteerd", english: "argued", category: "Daily Life" },
        { dutch: "uitgebreid", english: "expanded", category: "Daily Life" },
        { dutch: "aangepast", english: "adapted", category: "Daily Life" },
        { dutch: "verlaagd", english: "reduced", category: "Daily Life" },
        { dutch: "geïnsisteerd", english: "insisted", category: "Daily Life" },
        { dutch: "verkend", english: "explored", category: "Daily Life" },
        { dutch: "verhelderd", english: "clarified", category: "Daily Life" },
        { dutch: "versterkt", english: "strengthened", category: "Daily Life" },
        { dutch: "besproken", english: "discussed", category: "Daily Life" },
        { dutch: "bijgewerkt", english: "updated", category: "Daily Life" },
        { dutch: "geoptimaliseerd", english: "optimized", category: "Daily Life" },

        { dutch: "maatschappij", english: "society", category: "Family" },
        { dutch: "cultuur", english: "culture", category: "Family" },
        { dutch: "motivatie", english: "motivation", category: "Family" },
        { dutch: "uitdagingen", english: "challenges", category: "Family" },
        { dutch: "verwachtingen", english: "expectations", category: "Family" },

        { dutch: "op afstand", english: "remote", category: "Travel" },
        { dutch: "toekomst", english: "future", category: "Travel" },
        { dutch: "lange termijn", english: "long term", category: "Travel" },

        { dutch: "bovendien", english: "in addition", category: "Connectors" },
        { dutch: "daarom", english: "therefore", category: "Connectors" },
        { dutch: "ondanks", english: "despite", category: "Connectors" },
        { dutch: "hoewel", english: "although", category: "Connectors" },
        { dutch: "zelfs", english: "even", category: "Connectors" },
        { dutch: "opnieuw", english: "again", category: "Connectors" },
        { dutch: "voorzichtig", english: "carefully", category: "Connectors" }
    ]
};