export default [
    { nl: "wat zou je willen drinken", file: "que-te-gustaria-beber.mp3", en: "What would you like to drink?" },
    { nl: "hoe gaat het vandaag met je", file: "como-estas-hoy.mp3", en: "How are you today?" },
    { nl: "waar woon je", file: "donde-vives.mp3", en: "Where do you live?" },
    { nl: "wat wil je eten", file: "que-quieres-comer.mp3", en: "What do you want to eat?" },
    { nl: "heb je honger", file: "tienes-hambre.mp3", en: "Are you hungry?" },
    { nl: "wat doe je graag", file: "que-te-gusta-hacer.mp3", en: "What do you like to do?" },
    { nl: "hoe laat sta je op", file: "a-que-hora-te-levantas.mp3", en: "What time do you get up?" },
    { nl: "wil je vandaag uitgaan", file: "quieres-salir-hoy.mp3", en: "Do you want to go out today?" },
    { nl: "wat ben je aan het doen", file: "que-estas-haciendo.mp3", en: "What are you doing?" },
    { nl: "wil je een film kijken", file: "quieres-ver-una-pelicula.mp3", en: "Do you want to watch a movie?" },
    { nl: "waar is de badkamer", file: "donde-esta-el-bano.mp3", en: "Where is the bathroom?" },
    { nl: "welke muziek vind je leuk", file: "que-musica-te-gusta.mp3", en: "What music do you like?" },
    { nl: "wil je uitrusten", file: "quieres-descansar.mp3", en: "Do you want to rest?" },
    { nl: "wat is er in de keuken", file: "que-hay-en-la-cocina.mp3", en: "What is in the kitchen?" },
    { nl: "wil je naar het hotel gaan", file: "quieres-ir-al-hotel.mp3", en: "Do you want to go to the hotel?" },
    { nl: "welk fruit vind je lekker", file: "que-fruta-te-gusta.mp3", en: "What fruit do you like?" },
    { nl: "wil je meer Spaans leren", file: "quieres-aprender-mas-espanol.mp3", en: "Do you want to learn more Spanish?" },
    { nl: "wat kijk je op tv", file: "que-ves-en-la-television.mp3", en: "What do you watch on TV?" },
    { nl: "wil je brood met kaas", file: "quieres-pan-con-queso.mp3", en: "Do you want bread with cheese?" },
    { nl: "waar is je familie", file: "donde-esta-tu-familia.mp3", en: "Where is your family?" },
    { nl: "wil je met de bus gaan", file: "quieres-ir-en-autobus.mp3", en: "Do you want to go by bus?" },
    { nl: "wat doe je thuis", file: "que-haces-en-casa.mp3", en: "What do you do at home?" }
];

const CEFR_CONVERSATION_AUDIO_A2 = [
    { nl: "wat doe je normaal gesproken 's ochtends", file: "que-haces-normalmente-por-la-manana.mp3", en: "What do you normally do in the morning?" },
    { nl: "wat zou je vandaag willen proberen", file: "que-te-gustaria-probar-hoy.mp3", en: "What would you like to try today?" },
    { nl: "hoe laat ben je gisteravond aangekomen", file: "a-que-hora-llegaste-anoche.mp3", en: "What time did you arrive last night?" },
    { nl: "wat lunch je meestal", file: "que-almuerzas-normalmente.mp3", en: "What do you normally have for lunch?" },
    { nl: "welke film wil je zien", file: "que-pelicula-quieres-ver.mp3", en: "What movie do you want to watch?" },
    { nl: "welk bericht heb je ontvangen", file: "que-mensaje-recibiste.mp3", en: "What message did you receive?" },
    { nl: "wat ga je vanavond koken", file: "que-vas-a-cocinar-esta-noche.mp3", en: "What are you going to cook tonight?" },
    { nl: "welk huiswerk heb je vandaag", file: "que-tarea-tienes-hoy.mp3", en: "What homework do you have today?" },
    { nl: "wat wil je bezoeken tijdens je volgende reis", file: "que-quieres-visitar-en-tu-proximo-viaje.mp3", en: "What do you want to visit on your next trip?" },
    { nl: "rijd je vaak auto", file: "conduces-a-menudo.mp3", en: "Do you drive often?" },
    { nl: "waar wacht je vandaag op", file: "que-esperas-hoy.mp3", en: "What are you waiting for today?" },
    { nl: "wat zou je willen vergeten", file: "que-te-gustaria-olvidar.mp3", en: "What would you like to forget?" },
    { nl: "wat doe je voordat je gaat slapen", file: "que-haces-antes-de-dormir.mp3", en: "What do you do before sleeping?" },
    { nl: "wat doe je na de lunch", file: "que-haces-despues-del-almuerzo.mp3", en: "What do you do after lunch?" },
    { nl: "welk vervoermiddel gebruik je meestal", file: "que-transporte-usas-normalmente.mp3", en: "What transport do you normally use?" },
    { nl: "welke keuken vind je het lekkerst", file: "que-cocina-te-gusta-mas.mp3", en: "Which kitchen do you like more?" },
    { nl: "wat ben je nu aan het doen", file: "que-haces-ahora.mp3", en: "What are you doing now?" },
    { nl: "welke schoenen draag je vandaag", file: "que-zapatos-usas-hoy.mp3", en: "What shoes are you wearing today?" },
    { nl: "wat zou je morgen willen koken", file: "que-te-gustaria-cocinar-manana.mp3", en: "What would you like to cook tomorrow?" },
    { nl: "welke informatie heb je nodig", file: "que-informacion-necesitas.mp3", en: "What information do you need?" },
    { nl: "wat doe je als je thuiskomt", file: "que-haces-cuando-llegas-a-casa.mp3", en: "What do you do when you arrive home?" },
    { nl: "wat zou je dit jaar willen bezoeken", file: "que-te-gustaria-visitar-este-ano.mp3", en: "What would you like to visit this year?" }
];

const CEFR_CONVERSATION_AUDIO_B1 = [
    { nl: "wat heb je de laatste tijd geleerd", file: "que-has-aprendido-recientemente.mp3", en: "What have you learned recently?" },
    { nl: "wat ben je nu aan het studeren", file: "que-estas-estudiando-ahora.mp3", en: "What are you studying now?" },
    { nl: "aan welke ervaringen uit het verleden denk je het meest terug", file: "que-experiencias-pasadas-recuerdas-mas.mp3", en: "What past experiences do you remember most?" },
    { nl: "welke vaardigheden wil je verbeteren", file: "que-habilidades-quieres-mejorar.mp3", en: "What skills do you want to improve?" },
    { nl: "waar ben je deze week aan het werk", file: "que-estas-trabajando-esta-semana.mp3", en: "What are you working on this week?" },
    { nl: "wat voor soort gesprekken voel je vaak", file: "que-conversaciones-tienes-a-menudo.mp3", en: "What conversations do you often have?" },
    { nl: "wat heb je de laatste tijd gedaan", file: "que-has-estado-haciendo-ultimamente.mp3", en: "What have you been doing lately?" },
    { nl: "wat wil je deze maand bereiken", file: "que-quieres-conseguir-este-mes.mp3", en: "What do you want to achieve this month?" },
    { nl: "wat zou je willen blijven leren", file: "que-te-gustaria-continuar-aprendiendo.mp3", en: "What would you like to continue learning?" },
    { nl: "welk type communicatie is belangrijk voor jou", file: "que-tipo-de-comunicacion-es-importante-para-ti.mp3", en: "What type of communication is important to you?" },
    { nl: "wat heb je de laatste tijd gelezen", file: "que-has-estado-leyendo-ultimamente.mp3", en: "What have you been reading lately?" },
    { nl: "wat zou je morgen willen voorbereiden", file: "que-te-gustaria-preparar-manana.mp3", en: "What would you like to prepare tomorrow?" },
    { nl: "wat zou je dit jaar willen veranderen", file: "que-te-gustaria-cambiar-este-ano.mp3", en: "What would you like to change this year?" },
    { nl: "wat zou je willen blijven doen", file: "que-te-gustaria-seguir-haciendo.mp3", en: "What would you like to keep doing?" },
    { nl: "wat voor soort taken heb je deze week", file: "que-tipo-de-tareas-tienes-esta-semana.mp3", en: "What tasks do you have this week?" },
    { nl: "wat zou je vandaag willen vinden", file: "que-te-gustaria-encontrar-hoy.mp3", en: "What would you like to find today?" },
    { nl: "wat zou je deze maand willen annuleren", file: "que-te-gustaria-cancelar-este-mes.mp3", en: "What would you like to cancel this month?" },
    { nl: "wat zou je mee willen nemen naar de vergadering", file: "que-te-gustaria-traer-a-la-reunion.mp3", en: "What would you like to bring to the meeting?" },
    { nl: "wat ben je van plan om morgen te doen", file: "que-planeas-hacer-manana.mp3", en: "What do you plan to do tomorrow?" },
    { nl: "wat zou je beter willen begrijpen", file: "que-te-gustaria-entender-mejor.mp3", en: "What would you like to understand better?" },
    { nl: "wat zou je willen blijven beoordelen", file: "que-te-gustaria-seguir-revisando.mp3", en: "What would you like to keep reviewing?" }
];

const CEFR_CONVERSATION_AUDIO_B2 = [
    { nl: "welke strategie gebruik je om beter te leren", file: "que-estrategia-usas-para-aprender-mejor.mp3", en: "What strategy do you use to learn better?" },
    { nl: "hoe evalueer je jouw prestaties op het werk", file: "como-evaluas-tu-rendimiento-en-el-trabajo.mp3", en: "How do you evaluate your performance at work?" },
    { nl: "welk concept vind je de laatste tijd ingewikkeld", file: "que-concepto-te-parece-complicado-ultimamente.mp3", en: "What concept seems complicated to you lately?" },
    { nl: "welk risico vind je belangrijk in je werk", file: "que-riesgo-consideras-importante-en-tu-trabajo.mp3", en: "What risk do you consider important in your work?" },
    { nl: "welke mogelijkheid zou je willen verkennen", file: "que-posibilidad-te-gustaria-explorar.mp3", en: "What possibility would you like to explore?" },
    { nl: "welke situatie heeft je recentelijk geraakt", file: "que-situacion-te-ha-afectado-recientemente.mp3", en: "What situation has affected you recently?" },
    { nl: "hoe optimaliseer je elke dag je tijd", file: "como-optimizas-tu-tiempo-cada-dia.mp3", en: "How do you optimize your time each day?" },
    { nl: "welke professionele aanpak werkt het beste voor jou", file: "que-enfoque-profesional-te-funciona-mejor.mp3", en: "What professional approach works best for you?" },
    { nl: "welke taak zou je willen bijwerken", file: "que-tarea-te-gustaria-actualizar.mp3", en: "What task would you like to update?" },
    { nl: "wat heb je deze week geanalyseerd", file: "que-has-analizado-esta-semana.mp3", en: "What have you analyzed this week?" },
    { nl: "wat zou je met je team willen bespreken", file: "que-te-gustaria-discutir-con-tu-equipo.mp3", en: "What would you like to discuss with your team?" },
    { nl: "wat heb je deze maand bereikt", file: "que-has-logrado-este-mes.mp3", en: "What have you achieved this month?" },
    { nl: "welke cultuur vind je interessant om te verkennen", file: "que-cultura-te-interesa-explorar.mp3", en: "What culture are you interested in exploring?" },
    { nl: "welke uitdagingen ben je recentelijk tegengekomen", file: "que-desafios-has-enfrentado-recientemente.mp3", en: "What challenges have you faced recently?" },
    { nl: "welke verwachtingen heb je voor dit jaar", file: "que-expectativas-tienes-para-este-ano.mp3", en: "What expectations do you have for this year?" },
    { nl: "welke situatie zou je willen verhelderen", file: "que-situacion-te-gustaria-aclarar.mp3", en: "What situation would you like to clarify?" },
    { nl: "welk proces zou je willen optimaliseren", file: "que-proceso-te-gustaria-optimizar.mp3", en: "What process would you like to optimize?" },
    { nl: "welke informatie heb je recentelijk geëvalueerd", file: "que-informacion-has-evaluado-recientemente.mp3", en: "What information have you evaluated recently?" },
    { nl: "welk idee zou je willen versterken", file: "que-idea-te-gustaria-fortalecer.mp3", en: "What idea would you like to strengthen?" },
    { nl: "welk onderwerp zou je diepgaander willen bespreken", file: "que-tema-te-gustaria-discutir-mas-profundamente.mp3", en: "What topic would you like to discuss more deeply?" },
    { nl: "welke aanpak zou je dit jaar willen aanpassen", file: "que-enfoque-te-gustaria-adaptar-este-ano.mp3", en: "What approach would you like to adapt this year?" }
];