export default {
    "Open Cut Mining": [
        { dutch: "toegangsramp", english: "access ramp", category: "Open Cut Mining" },
        { dutch: "natuurlijke hellingshoek", english: "angle of repose", category: "Open Cut Mining" },
        { dutch: "boorworm-mijnbouw", english: "auger mining", category: "Open Cut Mining" },
        { dutch: "dieppraamgraafmachine", english: "backhoe excavator", category: "Open Cut Mining" },
        { dutch: "etage", english: "bench", category: "Open Cut Mining" },
        { dutch: "berm", english: "berm", category: "Open Cut Mining" },
        { dutch: "boorpatroon", english: "blast pattern", category: "Open Cut Mining" },
        { dutch: "startsnede", english: "box cut", category: "Open Cut Mining" },
        { dutch: "massale mijnbouw", english: "bulk mining", category: "Open Cut Mining" },
        { dutch: "vangberm", english: "catch bench", category: "Open Cut Mining" },
        { dutch: "rand", english: "crest", category: "Open Cut Mining" },
        { dutch: "bulldozerinlaat", english: "dozer trap", category: "Open Cut Mining" },
        { dutch: "kabelkraan", english: "dragline", category: "Open Cut Mining" },
        { dutch: "blaasgatboortoren", english: "drill rig (rotary blasthole)", category: "Open Cut Mining" },
        { dutch: "stortplaats", english: "dump / waste dump", category: "Open Cut Mining" },
        { dutch: "elektrische kabelgraafmachine", english: "electric rope shovel", category: "Open Cut Mining" },
        { dutch: "externe stortplaats", english: "ex-pit dump", category: "Open Cut Mining" },
        { dutch: "ontginningswand", english: "face", category: "Open Cut Mining" },
        { dutch: "gehaltecontrole", english: "grade control", category: "Open Cut Mining" },
        { dutch: "transportweg", english: "haul road", category: "Open Cut Mining" },
        { dutch: "hoge wand", english: "highwall", category: "Open Cut Mining" },
        { dutch: "in-pit breek- en transportsysteem", english: "in-pit crushing and conveying (IPCC)", category: "Open Cut Mining" },
        { dutch: "interne stortplaats", english: "in-pit dump", category: "Open Cut Mining" },
        { dutch: "etagehoogte", english: "lift", category: "Open Cut Mining" },
        { dutch: "laad- en transportsysteem", english: "load-and-haul", category: "Open Cut Mining" },
        { dutch: "lage wand", english: "lowwall", category: "Open Cut Mining" },
        { dutch: "levensduur van de mine", english: "mine life", category: "Open Cut Mining" },
        { dutch: "mijnplan", english: "mine plan", category: "Open Cut Mining" },
        { dutch: "mobiele crusher", english: "mobile crusher", category: "Open Cut Mining" },
        { dutch: "hoop opgeblazen materiaal", english: "muckpile", category: "Open Cut Mining" },
        { dutch: "dagbouw", english: "open-cut / open-pit", category: "Open Cut Mining" },
        { dutch: "deklang", english: "overburden", category: "Open Cut Mining" },
        { dutch: "perimeterbeveiliging", english: "perimeter bund", category: "Open Cut Mining" },
        { dutch: "groevebodem", english: "pit floor", category: "Open Cut Mining" },
        { dutch: "groevegrenzen", english: "pit limit / ultimate pit limit", category: "Open Cut Mining" },
        { dutch: "steengroeve", english: "quarry", category: "Open Cut Mining" },
        { dutch: "herbehandeling", english: "rehandle", category: "Open Cut Mining" },
        { dutch: "milieuherstel", english: "rehabilitation", category: "Open Cut Mining" },
        { dutch: "roterende boormachine", english: "rotary blasthole drill", category: "Open Cut Mining" },
        { dutch: "run-of-mine platform", english: "run-of-mine (rom) pad", category: "Open Cut Mining" },
        { dutch: "veiligheidswal", english: "safety bund", category: "Open Cut Mining" },
        { dutch: "grofzeven", english: "scalping", category: "Open Cut Mining" },
        { dutch: "taludstabiliteit", english: "slope stability", category: "Open Cut Mining" },
        { dutch: "deklang-ertsmengverhouding", english: "stripping ratio", category: "Open Cut Mining" },
        { dutch: "oppervlaktemijnbouwer", english: "surface miner", category: "Open Cut Mining" },
        { dutch: "taludvoet", english: "toe", category: "Open Cut Mining" },
        { dutch: "teelaarde afgraving", english: "topsoil stripping", category: "Open Cut Mining" },
        { dutch: "verkeersbeheersingsplan", english: "traffic management plan", category: "Open Cut Mining" },
        { dutch: "eindgroeve", english: "ultimate pit", category: "Open Cut Mining" },
        { dutch: "wiellader", english: "wheel loader", category: "Open Cut Mining" }
    ],
    "Underground Mining": [
        { dutch: "adit", english: "adit", category: "Underground Mining" },
        { dutch: "opvulling", english: "backfill", category: "Underground Mining" },
        { dutch: "blokcaving", english: "block caving", category: "Underground Mining" },
        { dutch: "blokpijler", english: "block pillar", category: "Underground Mining" },
        { dutch: "trechter", english: "drawbell", category: "Underground Mining" },
        { dutch: "trekpunt", english: "drawpoint", category: "Underground Mining" },
        { dutch: "inzakking", english: "caving", category: "Open Cut Mining" },
        { dutch: "dwarsgang", english: "crosscut", category: "Underground Mining" },
        { dutch: "gang", english: "drift", category: "Underground Mining" },
        { dutch: "onderliggende wand", english: "footwall", category: "Underground Mining" },
        { dutch: "hangende wand", english: "hanging wall", category: "Underground Mining" },
        { dutch: "langfrontmijnbouw", english: "longwall mining", category: "Underground Mining" },
        { dutch: "productieniveau", english: "production level", category: "Underground Mining" },
        { dutch: "blind schacht", english: "raise", category: "Underground Mining" },
        { dutch: "schacht", english: "shaft", category: "Underground Mining" },
        { dutch: "pijler", english: "stope", category: "Underground Mining" },
        { dutch: "bodemdaling", english: "subsidence", category: "Underground Mining" },
        { dutch: "ondersnijding", english: "undercut", category: "Underground Mining" },
        { dutch: "ondersnijdingsniveau", english: "undercut level", category: "Underground Mining" },
        { dutch: "blinde schacht omlaag", english: "winze", category: "Underground Mining" }
    ]
};