export default {
  
    "kan / kunt / kan": "can",
    "kopen": "buy",
    "bestellen": "order",
    "de / de / de / de": "the",
    "een / een": "a",
    "een / een": "an",
    "is / is": "is",
    "zijn / zijn": "are",
    "wil": "want",
    "heb nodig": "need",

   
    "ik kan": "I can",
    "jij kunt": "you can (informal)",
    "hij kan / zij kan / u kunt": "he / she / you (formal) can",
    "wij kunnen": "we can",
    "zij kunnen / jullie kunnen": "they / you all can",
    "jij wilt": "you want (informal)",
    "jij hebt nodig": "you need (informal)",
    "jij hebt": "you have (informal)",
    "jij doet / jij maakt": "you do / you make",
    "ik koop": "I buy",
    "jij koopt": "you buy",
    "ik bestel / ik vraag": "I order / I request",
    "jij bestelt": "you order",

     
    "goede": "good (fem.)",
    "goede": "good (plural)",
    "goede": "good (fem. plural)",
    "slechte": "bad (fem.)",
    "slechte": "bad (plural)",
    "slechte": "bad (fem. plural)",
    "nieuwe": "new (fem.)",
    "nieuwe": "new (plural)",
    "nieuwe": "new (fem. plural)",
    "kleine": "small (fem.)",
    "kleine": "small (plural)",
    "kleine": "small (fem. plural)",
    "koude": "cold (fem.)",
    "koude": "cold (plural)",
    "koude": "cold (fem. plural)",
    "grote": "big / large (plural)",
    "lange": "tall (plural)",
    "lange": "tall (fem. plural)",
    "schone": "clean (fem.)",
    "schone": "clean (plural)",

     
    "en": "and",
    "of": "or",
    "met": "with",
    "zonder": "without",
    "meer": "more",
    "weinig": "little",
    "alleen": "only / alone",
    "erg": "very",
    "dichtbij": "near",
    "voor": "for",
    "naar": "to",
    "in / op": "in / on",
    "voor / door": "for / by",
    "van": "of / from",
    "naar de": "to the",
    "van de": "of the",
    "maar": "but",
    "omdat": "because",
    "ook": "also",
    "dan": "then",
    "ja / als": "yes / if",
    "er is / er zijn": "there is / there are",
    "andere": "other / another",
    "andere (mannelijk)": "other / another (masc.)",
    "andere (plural)": "other / another (plural)",
    "andere (mannelijk plural)": "other / another (masc. plural)",
    "ondanks": "despite",
    "ondanks": "despite",
    "gunst": "favor",
    "alstublieft": "please",
    "terwijl": "while",
    "echter": "however",
    "over / bovenop": "about / on top of",
    "na": "after",
    "tijdens": "during",
    "bovendien": "in addition / furthermore",
    "dus": "therefore",
    "hoewel": "although",
    "zelfs": "even",
    "nog een keer": "again",

    
    "wat": "what",
    "wie": "who",
    "wanneer": "when",
    "hoe": "how",
    "welke": "which",
    "waar": "where",
    "waarom": "why",

    
    "de": "the",
    "de": "the",
    "de (plural)": "the (plural)",
    "de (fem. plural)": "the (fem. plural)",
    "een": "a / an",
    "een (fem.)": "a / an (fem.)",
    "enkele": "some",
    "enkele (fem.)": "some (fem.)",
    
    "mij / mezelf": "me / myself",
    "jou / jezelf": "you / yourself",
    "aan hem / aan haar": "to him / to her",
    "ons / onszelf": "us / ourselves",
    "aan hen": "to them",
    "het / hem": "it / him",
    "het / haar": "it / her",
    "hen (mannelijk)": "them (masc.)",
    "hen (vrouwelijk)": "them (fem.)",
    "dat / welke": "that / which",
    "hij": "he",
    "zij": "she",
    "ik": "I",
    "jij": "you (informal)",
    "wij": "we",
    "wij (fem.)": "we (fem.)",
    "zij": "they",
    "zij (fem.)": "they (fem.)",
    "jullie / u allen": "you all",
    "mijn": "my",
    "mijn (plural)": "my (plural)",
    "zijn / haar / hun / uw": "his / her / their / your",
    "zijn / haar / hun / uw (plural)": "his / her / their / your (plural)",
    "jouw": "your (possessive)",
    "jouw (plural)": "your (possessive plural)",
    "dit": "this (neutral)",
    "deze (mannelijk)": "this (masc.)",
    "deze (vrouwelijk)": "this (fem.)",
    "die (mannelijk)": "that (masc.)",
    "die (vrouwelijk)": "that (fem.)",
    "iets": "something",
    "alles": "everything / all",
    "alle (fem. plural)": "all (fem. plural)",
    "alle (masc. plural)": "all (masc. plural)",

    
    "is": "is",
    "ik ben": "I am",
    "jij bent": "you are",
    "wij zijn": "we are",
    "zij zijn / jullie zijn": "they are / you all are",
    "ik ben (locatie)": "I am (state/location)",
    "is / u bent": "is / you are (formal)",
    "jij bent": "you are (informal)",
    "wij zijn (locatie)": "we are (state/location)",
    "zij zijn (locatie)": "they are / you all are (state/location)",
    "was / ging": "was / went (past)",
    "was": "was (descriptive past)",
    "ik wil": "I want",
    "hij wil / zij wil": "he / she wants",
    "wij willen": "we want",
    "zij willen": "they want / you all want",
    "ik heb nodig": "I need",
    "hij heeft nodig / zij heeft nodig": "he / she needs",
    "wij hebben nodig": "we need",
    "zij hebben nodig": "they need",
    "ik heb": "I have",
    "hij heeft / zij heeft": "he / she has",
    "wij hebben": "we have",
    "zij hebben": "they have",
    "honger": "hunger",
    "bevalt": "likes / pleasing to",
    "bevallen": "they like / pleasing to (plural)",
    "zou willen": "would like",
    "ik zou willen": "I would like",
    "ik woon": "I live",
    "zij wonen": "they live",
    "hij werkt / zij werkt": "he / she works",
    "werkend": "working",
    "studerend": "studying",
    "lerend": "learning",
    "reparerend": "fixing",
    "lezend": "reading",
    "levend": "living",
    "wachtend": "waiting",
    "kijkend / ziend": "watching / seeing",
    "sprekend": "talking / speaking",
    "kokend": "cooking",
    "rijdend": "driving",
    "plannend": "planning",
    "ontbijtend": "eating breakfast",
    "komt aan": "arrives",
    "wij kwamen aan": "we arrived",
    "zij zullen aankomen": "they will arrive",
    "ik kom aan / hij komt aan": "I arrive / he or she arrives",
    "opent": "opens",
    "stelde voor": "suggested",
    "betoogden": "argued",
    "zij eindigden": "they finished",
    "drong aan": "insisted",
    "legde uit": "explained",
    "vroeg / bestelde": "asked for / requested",
    "hielp / zou helpen": "helped / would help",
    "zij plannen": "they plan",
    "ons aanpassen": "to adapt ourselves",
    "ons voorbereiden": "to prepare ourselves",
    "hij zal hebben / zij zal hebben": "he / she will have",
    "zij zullen zijn": "they will be",
    "voltooide": "completed",
    "bezocht": "visited",
    "vergat": "forgot",
    "belde": "called",
    "ik kocht": "I bought",
    "ik maakte schoon": "I cleaned",
    "ik schreef": "I wrote",
    "ik zal studeren": "I will study",
    "ik zal helpen": "I will help",
    "wij zullen doorgaan": "we will continue",
    "wij zullen eten": "we will eat",
    "weggaan": "to leave / to go away",

    
    "vandaag": "today",
    "morgen / ochtend": "tomorrow / morning",
    "gisteren": "yesterday",
    "gisteravond": "last night",
    "nu": "now",
    "altijd": "always",
    "nooit": "never",
    "al / nu": "already / now",
    "nog / nog steeds": "still / yet",
    "normaal gesproken": "normally",
    "binnenkort": "soon",
    "laat / middag": "late / afternoon",
    "vroeg": "early",
    "vaak": "often",
    "later": "later",
    "vanavond": "tonight",
    "om negen uur": "at nine",
    "duidelijk": "clearly",
    "langzaam": "slowly",
     
    "goed": "good",
    "goede": "good (fem.)",
    "goede": "good (plural)",
    "goede": "good (fem. plural)",
    "slecht": "bad",
    "slechte": "bad (fem.)",
    "slechte": "bad (plural)",
    "slechte": "bad (fem. plural)",
    "nieuw": "new",
    "nieuwe": "new (fem.)",
    "nieuwe": "new (plural)",
    "nieuwe": "new (fem. plural)",
    "klein": "small",
    "kleine": "small (fem.)",
    "kleine": "small (plural)",
    "kleine": "small (fem. plural)",
    "heet": "hot",
    "hete": "hot (plural)",
    "koud": "cold",
    "koude": "cold (fem.)",
    "koude": "cold (plural)",
    "koude": "cold (fem. plural)",
    "blij": "happy",
    "blije": "happy (plural)",
    "moeilijk": "difficult",
    "moeilijke": "difficult (plural)",
    "makkelijk": "easy",
    "makkelijke": "easy (plural)",
    "duidelijke": "clear / bright (fem.)",
    "duidelijk": "clear / bright (masc.)",
    "duidelijke": "clear (plural)",
    "duidelijke": "clear (fem. plural)",
    "groot": "big / large",
    "grote": "big / large (plural)",
    "lang / hoog": "tall / high",
    "lange": "tall (fem.)",
    "lange": "tall (plural)",
    "lange": "tall (fem. plural)",
    "heerlijke": "delicious (fem.)",
    "heerlijk": "delicious (masc.)",
    "vriendelijk": "kind / nice",
    "vriendelijke": "kind / nice (plural)",
    "schone": "clean (fem.)",
    "schoon": "clean (masc.)",
    "rode": "red (fem.)",
    "rood": "red (masc.)",
    "vertraagd": "delayed / late",
    "vertraagde": "delayed (fem.)",
    "realistisch": "realistic",
    "realistische": "realistic (plural)",
    "professioneel": "professional",
    "professionele": "professional (plural)",
    "innovatieve": "innovative (fem.)",
    "innovatief": "innovative (masc.)",
    "onnodige": "unnecessary (plural)",
    "onnodig": "unnecessary",
    "riskante": "risky (fem.)",
    "riskant": "risky (masc.)",
    "capabel": "capable",
    "capabele": "capable (plural)",
    "effectief": "effective",
    "effectieve": "effective (fem.)",
    "positief": "positive",
    "positieve": "positive (fem.)",
    "positieve": "positive (plural)",
    "ingewikkeld": "complicated",
    "ingewikkelde": "complicated (fem.)",
    "belangrijk": "important",
    "belangrijke": "important (plural)",
    "anders": "different",
    "andere": "different (plural)",
    "beter": "better",
    "betere": "better / best (plural)",
    "uitstekend": "excellent",
    "uitstekende": "excellent (plural)",
    "mogelijk": "possible",
    "mogelijke": "possible (plural)",
    "volgende": "next",
    "volgende (fem.)": "next (fem.)",

    
    "elf": "eleven",
    "twaalf": "twelve",
    "dertien": "thirteen",
    "veertien": "fourteen",
    "vijftien": "fifteen",
    "zestien": "sixteen",
    "zeventien": "seventeen",
    "achttien": "eighteen",
    "negentien": "nineteen",
    "twintig": "twenty"
};  
